#!/usr/bin/env python3
"""Generates src/data/exploreRecipes.ts with ~600 real recipes."""

import json, random

# Curated Unsplash photo IDs by food category
IMAGES = {
    "stir_fry":   ["VgezwL1xw5M","708OpfCW4H8","Jbns6GiAisU","kdB88FBL8bs","oT7_v-I0hHg"],
    "curry":      ["tsQhEvzU6MQ","sqcH2q7lkvo","tWkA48kabZE","vgTntT8PmIM","ncXvQnrmStA","OterGMpkdsM"],
    "noodles":    ["B3VTHOLngWA","GGXmiKp52qU","08aic3qPcag","_wBJ0cvKhIE","sE4UdOjoYr4"],
    "soup":       ["vPMQl71yFDI","NFQi_2HUNRI","v3AAMtzK2qE","5DsTEP06774","AXWXzGUdLLo"],
    "rice":       ["ysmeQt1dzcw","-bxGTjZ6dt8","sWyasAoe25k","z32XV0TGSzc","AvJX9o6w35U"],
    "pasta":      ["t3B9LxHcybc","bYSvpF8NBmE","QuFm328PV88","b29Qdj7zc5g"],
    "pizza":      ["OW5sCIT3H9o","L4W1uX1xwlQ","wgq8NVyXsYY","p7Q36vPBFs8","52jG7-FN22Y"],
    "sushi":      ["5Gte2_TlS_A","ZygmvOHnYLU","iIS1SIO5_aY","yZHY8E6_ld0"],
    "grilled":    ["RbI-U-WRuLw","kctt4tL1dkE","uIiMSu88RZQ","J0ysqzmpVac","m1YOztVo6MA","ofXy_NRwyjI","ooUW0of6ZpM"],
    "tacos":      ["3R9mIWSbYKo","7sStoaxfJh0"],
    "salad":      ["IGfIGP5ONV0","KPDbRyFOTnE","-ftWfohtjNw","V2Kw-YC7Cls"],
    "eggs":       ["KD93b4XevCQ","diDja86YL_M"],
    "burger":     ["OuEakbCRtDk","pu6b4yIlQF4","3tL4vtrFqTQ","pnV8uZlFWrA"],
    "dessert":    ["kPxsqUGneXQ","s52eRev_J_A","OnOBeFDIJC8","uG1jwfpCRhg","tCnOMWITk_4"],
    "bread":      ["YUQEo7ajeLA","52jG7-FN22Y"],
    "seafood":    ["byTYXNHeVoU","WERPqT_E5jE"],
    "stew":       ["7-TOCB28rms","al9eh9QkdPA"],
    "bowl":       ["diDja86YL_M","IWwZUVAHsmo","4f4YZfDMLeU"],
}

def img(category):
    ids = IMAGES.get(category, IMAGES["curry"])
    return f"https://images.unsplash.com/photo-{random.choice(ids)}?w=480&h=320&fit=crop&q=80"

R = []

def add(id, title, cuisine, cuisineId, region, imgCat, time, diff, diets, tags, servings, ingredients, instructions, cal, prot, carbs, fat, note=None):
    R.append({
        "id": f"gen-{id}",
        "source": "local",
        "sourceUrl": "",
        "title": title,
        "cuisine": cuisine,
        "cuisineId": cuisineId,
        "region": region,
        "image": img(imgCat),
        "mealType": None,
        "dishType": None,
        "totalTimeMinutes": time,
        "servings": servings,
        "difficulty": diff,
        "rating": round(random.uniform(4.1, 4.9), 1),
        "diets": diets,
        "tags": tags,
        "ingredients": [{"name": i[0], "amount": i[1], "unit": None} for i in ingredients],
        "instructions": instructions,
        "calories": cal,
        "protein": prot,
        "carbs": carbs,
        "fat": fat,
        "culturalNote": note,
    })

# ─── CHINESE ──────────────────────────────────────────────────────────────────
add("cn-001","Kung Pao Chicken","Chinese","chinese","East Asian","stir_fry",30,"Medium",[],["spicy","stir-fry","sichuan"],4,[("chicken breast","500g"),("peanuts","80g"),("dried red chillies","10"),("soy sauce","3 tbsp"),("Sichuan peppercorns","1 tsp"),("garlic","3 cloves"),("ginger","1 tsp"),("scallions","3"),("cornstarch","2 tsp"),("sesame oil","1 tsp")],["Cube chicken, marinate with soy sauce and cornstarch 10 min.","Stir-fry dried chillies and Sichuan peppercorns in hot wok 30 sec.","Add chicken, stir-fry 4 min until golden.","Add garlic, ginger, sauce. Toss with peanuts and scallions."],380,34,14,21,"Named after Qing Dynasty governor Ding Baozhen. The mala (numbing-spicy) flavour is the soul of Sichuan cooking.")
add("cn-002","Mapo Tofu","Chinese","chinese","East Asian","curry",25,"Easy",["vegetarian"],["tofu","spicy","sichuan"],3,[("silken tofu","400g"),("doubanjiang","2 tbsp"),("ground pork","150g"),("fermented black beans","1 tbsp"),("Sichuan peppercorn","½ tsp"),("garlic","4 cloves"),("ginger","1 tsp"),("chicken stock","200ml"),("scallions","2")],["Gently cube tofu, simmer in salted water 2 min, drain.","Stir-fry pork until browned. Add doubanjiang and black beans.","Add garlic, ginger, stock, and tofu. Simmer 5 min.","Thicken with cornstarch, finish with Sichuan pepper and scallions."],290,22,8,18,"Pockmarked old woman's tofu — a beloved Chengdu classic since the 1860s.")
add("cn-003","Char Siu Pork","Chinese","chinese","East Asian","grilled",90,"Medium",[],["bbq","cantonese","pork"],4,[("pork belly","800g"),("hoisin sauce","3 tbsp"),("honey","2 tbsp"),("soy sauce","2 tbsp"),("Shaoxing wine","2 tbsp"),("five-spice powder","1 tsp"),("red food colouring","few drops")],["Mix all marinade ingredients. Coat pork and marinate overnight.","Roast at 200°C for 25 min, basting every 10 min.","Brush with honey glaze and broil 5 min until caramelised.","Rest 10 min, slice thinly across the grain."],480,32,24,28,"Cantonese BBQ pork — the backbone of Hong Kong's char siu bao and rice noodle rolls.")
add("cn-004","Xiao Long Bao","Chinese","chinese","East Asian","stir_fry",90,"Hard",[],["dumplings","shanghai","soup"],4,[("pork mince","400g"),("pork skin gelatin","200g"),("napa cabbage","100g"),("ginger","2 tsp"),("soy sauce","2 tbsp"),("Shaoxing wine","1 tbsp"),("sesame oil","1 tsp"),("dumpling wrappers","24")],["Dissolve pork skin gelatin in hot water, chill until set, dice.","Mix pork with gelatin dice, cabbage, ginger, soy, wine.","Pleat 16 folds into thin round wrappers.","Steam 8 min in bamboo steamer. Serve with ginger-vinegar."],180,14,18,6,"Soup dumplings from Shanghai — the gelatin melts into hot broth inside as they steam.")
add("cn-005","Wonton Soup","Chinese","chinese","East Asian","soup",40,"Medium",[],["wontons","soup","cantonese"],4,[("pork mince","300g"),("shrimp","100g"),("wonton wrappers","24"),("chicken broth","1L"),("ginger","2 slices"),("scallions","4"),("soy sauce","2 tbsp"),("sesame oil","1 tsp")],["Mix pork, shrimp, ginger, soy sauce for filling.","Place 1 tsp filling in wrapper, fold into wonton shape.","Bring broth to boil with ginger and scallions.","Cook wontons in broth 4 min until floating. Season and serve."],280,18,24,10)
add("cn-006","Peking Duck","Chinese","chinese","East Asian","grilled",240,"Hard",[],["duck","beijing","festive"],4,[("whole duck","2kg"),("maltose syrup","3 tbsp"),("five-spice powder","1 tsp"),("hoisin sauce","4 tbsp"),("thin pancakes","16"),("cucumber","1"),("scallions","6")],["Hang duck to air-dry 12-24 hours in a cool place.","Baste with maltose syrup and roast at 200°C for 1 hr 20 min.","Slice crispy skin and meat at the table.","Serve wrapped in thin pancakes with hoisin, cucumber, scallion."],620,38,30,38,"The pride of Beijing banquets since the imperial era.")
add("cn-007","Dan Dan Noodles","Chinese","chinese","East Asian","noodles",25,"Medium",["vegan-option"],["noodles","sichuan","spicy"],2,[("noodles","200g"),("chilli oil","3 tbsp"),("sesame paste","2 tbsp"),("soy sauce","2 tbsp"),("Chinkiang vinegar","1 tbsp"),("garlic","2 cloves"),("scallions","3"),("peanuts","30g")],["Cook noodles until al dente.","Mix chilli oil, sesame paste, soy, vinegar, garlic into sauce.","Toss hot noodles with sauce.","Top with scallions and crushed peanuts."],420,14,52,18)
add("cn-008","Steamed Fish with Ginger","Chinese","chinese","East Asian","seafood",20,"Easy",[],["fish","steamed","cantonese"],2,[("whole sea bass","600g"),("ginger","3 inch piece"),("scallions","4 stalks"),("soy sauce","3 tbsp"),("sesame oil","1 tbsp"),("cooking oil","2 tbsp")],["Score fish. Stuff cavity with half the ginger.","Steam over high heat 8-10 min.","Pour away liquid. Top with remaining ginger and scallion.","Heat oil until smoking, pour over fish. Add soy sauce."],220,32,4,8)
add("cn-009","Egg Fried Rice","Chinese","chinese","East Asian","stir_fry",15,"Easy",["vegetarian"],["rice","quick","dorm-friendly"],2,[("day-old rice","2 cups"),("eggs","2"),("scallions","3"),("soy sauce","2 tbsp"),("vegetable oil","1 tbsp"),("sesame oil","½ tsp"),("frozen peas","¼ cup")],["Break up cold rice. Scramble eggs in wok, set aside.","Add rice, stir-fry 3 min on high heat.","Return eggs, add soy sauce and peas.","Finish with sesame oil and scallions."],380,12,58,10)
add("cn-010","Hot and Sour Soup","Chinese","chinese","East Asian","soup",30,"Easy",["vegetarian-option"],["soup","sour","tofu"],4,[("silken tofu","200g"),("wood ear mushrooms","50g"),("bamboo shoots","100g"),("egg","1"),("rice vinegar","3 tbsp"),("soy sauce","2 tbsp"),("white pepper","1 tsp"),("cornstarch","2 tbsp"),("chicken stock","1L")],["Simmer stock with mushrooms and bamboo shoots.","Add tofu. Whisk egg and drizzle in slowly.","Season with vinegar, soy, white pepper.","Thicken with cornstarch slurry."],120,8,14,3)

# ─── JAPANESE ─────────────────────────────────────────────────────────────────
add("jp-001","Tonkotsu Ramen","Japanese","japanese","East Asian","noodles",270,"Hard",[],["ramen","pork","umami","comfort"],4,[("pork trotters","1kg"),("pork belly","500g"),("fresh ramen noodles","400g"),("soft-boiled eggs","4"),("nori","4 sheets"),("scallions","4"),("bamboo shoots","100g"),("soy sauce","4 tbsp"),("mirin","2 tbsp")],["Blanch trotters 5 min, discard water.","Simmer trotters in 3L water for 4 hr until broth is milky.","Braise pork belly in soy-mirin at 150°C for 2 hr.","Cook noodles, assemble with broth, pork, egg, nori."],720,42,65,28,"Born in Kurume, Fukuoka in 1937 — aggressive boiling emulsifies fat and collagen into the cloud-white broth.")
add("jp-002","Chicken Teriyaki","Japanese","japanese","East Asian","grilled",25,"Easy",[],["grilled","sweet","weeknight"],2,[("chicken thighs","400g"),("soy sauce","3 tbsp"),("mirin","3 tbsp"),("sake","1 tbsp"),("sugar","1 tbsp"),("sesame seeds","1 tsp")],["Combine soy sauce, mirin, sake, sugar for teriyaki sauce.","Score chicken and fry skin-side down 6 min.","Flip, add sauce, reduce until sticky. Slice and serve over rice."],410,38,14,22,"Teri means shine — the glaze from reduced soy-mirin is the defining touch.")
add("jp-003","Miso Soup","Japanese","japanese","East Asian","soup",10,"Easy",["vegetarian","vegan"],["soup","miso","dashi","quick"],4,[("dashi stock","1L"),("white miso paste","3 tbsp"),("silken tofu","200g"),("dried wakame","2 tbsp"),("scallions","2")],["Rehydrate wakame in cold water.","Heat dashi until just below boiling. Do not boil.","Dissolve miso in a ladle of broth, return to pot.","Add tofu and wakame. Serve with scallions."],60,5,8,2)
add("jp-004","Tempura","Japanese","japanese","East Asian","seafood",30,"Medium",[],["fried","crispy","light"],4,[("shrimp","300g"),("broccoli","1 head"),("sweet potato","1"),("ice-cold water","200ml"),("flour","150g"),("egg yolk","1"),("vegetable oil","for frying"),("dashi","200ml"),("soy sauce","2 tbsp"),("mirin","2 tbsp")],["Mix ice water, egg yolk, and flour just until combined (lumpy is fine).","Heat oil to 170°C. Dip vegetables and shrimp in batter.","Fry 2-3 min until golden and light.","Serve with dipping broth made from dashi, soy, mirin."],380,22,42,14,"The batter's airiness comes from the ice-cold water and deliberate undermixing.")
add("jp-005","Gyoza","Japanese","japanese","East Asian","stir_fry",40,"Medium",[],["dumplings","pan-fried","pork"],4,[("pork mince","300g"),("napa cabbage","200g"),("garlic","3 cloves"),("ginger","1 tsp"),("soy sauce","2 tbsp"),("sesame oil","1 tbsp"),("gyoza wrappers","24"),("vegetable oil","2 tbsp")],["Salt and squeeze moisture from cabbage.","Mix pork, cabbage, garlic, ginger, soy, sesame oil.","Fill and pleat wrappers, flatten bases.","Pan-fry 2 min, add water, steam-cook covered 3 min, uncover until crispy."],280,18,28,10)
add("jp-006","Oyakodon","Japanese","japanese","East Asian","rice",20,"Easy",[],["rice bowl","egg","chicken","comfort"],2,[("chicken thighs","300g"),("onion","1"),("eggs","3"),("dashi","200ml"),("soy sauce","3 tbsp"),("mirin","2 tbsp"),("sugar","1 tsp"),("steamed rice","2 bowls")],["Slice chicken and onion. Simmer in dashi, soy, mirin, sugar.","Add chicken, cook 5 min.","Drizzle beaten eggs in a spiral over simmering broth.","Cover 1 min, slide over rice bowls."],480,32,52,12,"Oyako means parent and child — chicken and egg together in one bowl.")
add("jp-007","Katsu Curry","Japanese","japanese","East Asian","curry",40,"Medium",[],["curry","pork","comfort"],2,[("pork loin","2 slices"),("S&B curry roux","½ block"),("potato","2"),("carrot","1"),("onion","1"),("panko breadcrumbs","1 cup"),("egg","1"),("flour","2 tbsp"),("oil","for frying")],["Coat pork in flour, egg, panko. Deep fry until golden.","Simmer diced veg in 500ml water until tender.","Add curry roux cubes and stir until dissolved.","Slice tonkatsu, place over rice beside curry sauce."],680,38,72,22)
add("jp-008","Takoyaki","Japanese","japanese","East Asian","stir_fry",30,"Medium",[],["octopus","street food","osaka"],4,[("octopus","200g"),("takoyaki batter mix","200g"),("eggs","2"),("dashi","300ml"),("scallions","4"),("pickled ginger","50g"),("takoyaki sauce","4 tbsp"),("mayo","4 tbsp"),("bonito flakes","handful")],["Make batter with mix, eggs, and dashi.","Pour into takoyaki pan. Add octopus, scallion, ginger to each.","Rotate with pick every 2 min until round and golden.","Top with sauce, mayo, bonito flakes."],240,14,28,9)
add("jp-009","Beef Udon","Japanese","japanese","East Asian","noodles",25,"Easy",[],["noodles","beef","comfort"],2,[("udon noodles","400g"),("beef sirloin","200g"),("dashi","800ml"),("soy sauce","3 tbsp"),("mirin","2 tbsp"),("sugar","1 tsp"),("scallions","3"),("seven spice","½ tsp")],["Slice beef paper-thin. Blanch briefly in boiling water.","Simmer dashi with soy, mirin, sugar.","Cook udon, drain. Add to broth.","Top with beef and scallions."],480,28,58,12)
add("jp-010","Tamagoyaki","Japanese","japanese","East Asian","eggs",15,"Medium",["vegetarian"],["egg","breakfast","bento"],2,[("eggs","4"),("dashi","3 tbsp"),("soy sauce","1 tsp"),("mirin","1 tsp"),("sugar","1 tsp"),("oil","1 tsp")],["Whisk eggs with dashi, soy, mirin, sugar.","Heat lightly oiled rectangular pan. Pour ⅓ of mix, tilt to coat.","When half-set, roll from one end. Push roll to one side.","Repeat with remaining egg, rolling over previous layers. Cool and slice."],120,10,6,8)

# ─── KOREAN ───────────────────────────────────────────────────────────────────
add("kr-001","Bibimbap","Korean","korean","East Asian","bowl",40,"Medium",["vegetarian"],["rice bowl","iconic","gochujang"],2,[("steamed rice","2 cups"),("spinach","100g"),("bean sprouts","100g"),("carrots","1"),("zucchini","½"),("shiitake mushrooms","6"),("eggs","2"),("gochujang","2 tbsp"),("sesame oil","2 tsp")],["Blanch and season each vegetable separately with sesame oil and garlic.","Fry or poach eggs.","Arrange vegetables over rice in sections. Place egg on top.","Add gochujang. Mix everything together before eating."],480,18,72,14,"Mixed rice — a tradition of combining leftover side dishes on New Year's Eve.")
add("kr-002","Bulgogi","Korean","korean","East Asian","grilled",30,"Easy",[],["beef","bbq","sweet"],4,[("beef ribeye","600g"),("soy sauce","4 tbsp"),("pear","½"),("sugar","1 tbsp"),("sesame oil","1 tbsp"),("garlic","4 cloves"),("ginger","1 tsp"),("scallions","3"),("sesame seeds","1 tbsp")],["Slice beef paper-thin across grain.","Blend pear with soy, sugar, garlic, ginger for marinade.","Marinate beef 30 min minimum.","Grill or pan-fry over high heat. Finish with sesame seeds."],320,28,18,16)
add("kr-003","Kimchi Jjigae","Korean","korean","East Asian","stew",30,"Easy",["vegetarian-option"],["stew","kimchi","spicy","comfort"],3,[("aged kimchi","300g"),("pork belly","200g"),("tofu","200g"),("gochugaru","1 tbsp"),("gochujang","1 tbsp"),("garlic","3 cloves"),("sesame oil","1 tsp"),("scallions","3")],["Stir-fry pork and kimchi together 5 min.","Add water to cover, bring to boil.","Add tofu, gochugaru, gochujang, garlic.","Simmer 20 min. Finish with sesame oil and scallions."],380,24,14,22,"Aged sour kimchi makes the best jjigae — the funk deepens the broth.")
add("kr-004","Tteokbokki","Korean","korean","East Asian","stir_fry",20,"Easy",["vegan"],["rice cakes","spicy","street food"],2,[("rice cakes","400g"),("gochujang","3 tbsp"),("gochugaru","1 tsp"),("soy sauce","1 tbsp"),("sugar","1 tbsp"),("fish cakes","100g"),("scallions","3"),("sesame seeds","1 tsp")],["Soak rice cakes in cold water 10 min.","Mix gochujang, gochugaru, soy sauce, sugar with 300ml water.","Simmer sauce, add rice cakes and fish cakes.","Cook 10 min until sauce thickens and coats. Top with sesame."],380,8,72,4,"The quintessential Korean street food — found at every pojangmacha food stall.")
add("kr-005","Korean Fried Chicken","Korean","korean","East Asian","grilled",40,"Medium",[],["chicken","crispy","sweet"],4,[("chicken wings","1kg"),("cornstarch","4 tbsp"),("garlic powder","1 tsp"),("oil for frying","",""),("gochujang","2 tbsp"),("honey","2 tbsp"),("soy sauce","1 tbsp"),("garlic","3 cloves"),("sesame seeds","1 tbsp")],["Coat wings in cornstarch mixture.","Fry at 170°C for 10 min. Drain. Fry again at 190°C for 5 min.","Mix gochujang, honey, soy, garlic for sauce.","Toss hot wings in sauce. Garnish with sesame."],520,32,38,24)
add("kr-006","Japchae","Korean","korean","East Asian","noodles",40,"Medium",["vegetarian"],["glass noodles","stir-fry","festive"],4,[("glass noodles","200g"),("beef","150g"),("spinach","100g"),("carrots","1"),("onion","1"),("shiitake mushrooms","5"),("soy sauce","3 tbsp"),("sesame oil","2 tbsp"),("sugar","1 tbsp"),("sesame seeds","1 tbsp")],["Soak and boil glass noodles, season with soy and sesame.","Stir-fry each vegetable and beef separately.","Combine all with noodles. Season with soy, sesame, sugar.","Toss well. Serve warm or at room temperature."],380,14,62,10)
add("kr-007","Sundubu Jjigae","Korean","korean","East Asian","stew",25,"Easy",[],["soft tofu","spicy","stew"],2,[("soft tofu","350g"),("clams","200g"),("gochugaru","2 tbsp"),("gochujang","1 tbsp"),("pork","100g"),("garlic","3 cloves"),("egg","1"),("scallions","2"),("sesame oil","1 tsp")],["Stir-fry pork with gochugaru and garlic.","Add water or stock, gochujang, and clams.","Add soft tofu in large pieces. Simmer 5 min.","Crack egg directly into boiling stew. Finish with sesame oil."],280,20,10,16)
add("kr-008","Samgyeopsal","Korean","korean","East Asian","grilled",25,"Easy",[],["pork belly","bbq","ssam"],4,[("pork belly slices","600g"),("garlic","1 head"),("green chillies","4"),("sesame oil","2 tbsp"),("salt","1 tsp"),("ssam jang (paste)","4 tbsp"),("perilla leaves","20"),("lettuce","20 leaves")],["Grill thick pork belly slices on tabletop grill.","Grill garlic and chillies alongside.","Wrap pork in lettuce or perilla with garlic, chilli, ssam jang.","Eat in one bite."],580,30,8,46)

# ─── THAI ─────────────────────────────────────────────────────────────────────
add("th-001","Pad Thai","Thai","thai","Southeast Asian","noodles",30,"Medium",[],["noodles","street food","tamarind"],2,[("rice noodles","200g"),("shrimp","200g"),("tofu","100g"),("eggs","2"),("bean sprouts","1 cup"),("scallions","3"),("roasted peanuts","3 tbsp"),("tamarind paste","3 tbsp"),("fish sauce","3 tbsp"),("palm sugar","2 tbsp")],["Soak noodles in cold water 20 min.","Stir-fry tofu until golden. Add shrimp. Scramble in eggs.","Add noodles and tamarind sauce. Toss well.","Serve topped with peanuts, scallions, lime, and chilli."],520,28,62,18,"Promoted as Thailand's national dish in the 1940s — tamarind is the secret to the sour-sweet balance.")
add("th-002","Green Curry","Thai","thai","Southeast Asian","curry",40,"Easy",[],["curry","coconut","aromatic"],4,[("green curry paste","3 tbsp"),("coconut milk","400ml"),("chicken breast","400g"),("Thai eggplant","200g"),("Thai basil","1 cup"),("fish sauce","2 tbsp"),("palm sugar","1 tbsp"),("kaffir lime leaves","4")],["Fry curry paste in coconut cream until fragrant.","Add chicken, cook 5 min. Pour in coconut milk.","Add eggplant and kaffir lime leaves. Simmer 8 min.","Season with fish sauce and palm sugar. Finish with Thai basil."],380,28,12,24)
add("th-003","Tom Yum Goong","Thai","thai","Southeast Asian","soup",25,"Easy",[],["soup","spicy","sour","shrimp"],4,[("shrimp","300g"),("lemongrass","3 stalks"),("galangal","4 slices"),("kaffir lime leaves","6"),("Thai chillies","5"),("mushrooms","150g"),("fish sauce","3 tbsp"),("lime juice","3 tbsp"),("chicken stock","1L")],["Bruise lemongrass, galangal, and kaffir lime leaves.","Simmer aromatics in stock 5 min.","Add mushrooms and shrimp. Cook 3 min.","Season with fish sauce and lime juice. Add chillies."],140,20,8,3)
add("th-004","Massaman Curry","Thai","thai","Southeast Asian","curry",60,"Medium",[],["curry","beef","peanut","mild"],4,[("beef chuck","600g"),("massaman curry paste","3 tbsp"),("coconut milk","400ml"),("potatoes","300g"),("peanuts","80g"),("onion","2"),("tamarind paste","2 tbsp"),("fish sauce","2 tbsp"),("palm sugar","2 tbsp")],["Brown beef in coconut oil. Remove.","Fry curry paste, add coconut milk. Return beef.","Add potatoes, onion, peanuts, tamarind. Simmer 40 min.","Season with fish sauce and palm sugar."],580,32,42,28,"Influenced by Muslim spice traders — mildly spiced with cinnamon, cardamom, and star anise.")
add("th-005","Som Tum","Thai","thai","Southeast Asian","salad",15,"Easy",["vegan"],["papaya","salad","spicy"],2,[("green papaya","300g"),("cherry tomatoes","100g"),("green beans","80g"),("dried shrimp","2 tbsp"),("peanuts","30g"),("garlic","2 cloves"),("Thai chillies","3"),("fish sauce","2 tbsp"),("lime juice","3 tbsp"),("palm sugar","1 tbsp")],["Pound garlic and chillies in mortar.","Add green beans, pound lightly.","Add papaya, tomatoes, dried shrimp, peanuts.","Season with fish sauce, lime, palm sugar. Toss."],120,5,22,3)
add("th-006","Pad Kra Pao","Thai","thai","Southeast Asian","stir_fry",15,"Easy",[],["basil","stir-fry","quick"],2,[("pork mince","400g"),("Thai basil","2 cups"),("garlic","4 cloves"),("Thai chillies","5"),("oyster sauce","2 tbsp"),("fish sauce","1 tbsp"),("soy sauce","1 tbsp"),("sugar","½ tsp"),("fried eggs","2")],["Fry garlic and chillies in wok until fragrant.","Add pork, stir-fry until cooked through.","Add oyster sauce, fish sauce, soy, sugar. Toss.","Add Thai basil and toss off heat. Top with fried egg."],380,28,12,22)
add("th-007","Khao Man Gai","Thai","thai","Southeast Asian","rice",50,"Easy",[],["chicken","rice","broth"],4,[("whole chicken","1.5kg"),("jasmine rice","2 cups"),("garlic","6 cloves"),("ginger","4 slices"),("coriander roots","3"),("fermented bean curd sauce","4 tbsp"),("ginger sauce","4 tbsp"),("cucumber","1")],["Poach chicken in water with garlic, ginger, coriander 45 min.","Cook rice in the poaching stock.","Slice chicken. Serve over rice with cucumber.","Serve with two dipping sauces made from fermented bean curd and ginger."],440,34,48,10)
add("th-008","Mango Sticky Rice","Thai","thai","Southeast Asian","dessert",30,"Easy",["vegan","gluten-free"],["dessert","mango","sweet","coconut"],2,[("glutinous rice","1 cup"),("coconut milk","300ml"),("sugar","3 tbsp"),("salt","½ tsp"),("ripe mango","2"),("sesame seeds","1 tsp")],["Soak sticky rice 4 hr, steam 20 min until tender.","Heat coconut milk with sugar and salt. Mix ⅔ into hot rice.","Let stand 10 min.","Serve rice alongside sliced mango. Drizzle remaining coconut milk."],380,5,70,8)

# ─── VIETNAMESE ───────────────────────────────────────────────────────────────
add("vn-001","Beef Pho","Vietnamese","vietnamese","Southeast Asian","soup",210,"Hard",[],["soup","noodles","aromatic","beef"],6,[("beef marrow bones","1.5kg"),("beef brisket","500g"),("rice noodles","400g"),("onion charred","2"),("ginger charred","1 piece"),("star anise","5"),("cinnamon","2 sticks"),("fish sauce","3 tbsp"),("bean sprouts","2 cups"),("fresh herbs","1 bunch")],["Blanch bones, rinse. Char onion and ginger.","Simmer bones with spices 3–4 hr.","Strain broth, season with fish sauce.","Cook noodles, serve in broth with sliced beef and herbs."],430,36,48,10,"Vietnam's national dish — the clear, star anise-scented broth takes hours but is worth every minute.")
add("vn-002","Bánh Mì","Vietnamese","vietnamese","Southeast Asian","bread",20,"Easy",[],["sandwich","street food","fusion"],2,[("baguette","2"),("pork belly","200g"),("pâté","50g"),("mayo","2 tbsp"),("pickled daikon","100g"),("pickled carrots","100g"),("cucumber","½"),("jalapeños","4"),("cilantro","handful")],["Char siu or roast pork belly with soy and five spice.","Spread pâté and mayo inside sliced baguette.","Layer pork, pickled veg, cucumber, jalapeños, cilantro."],480,24,48,18,"The baguette comes from French colonialism; the Vietnamese turned it into their own masterpiece.")
add("vn-003","Fresh Spring Rolls","Vietnamese","vietnamese","Southeast Asian","salad",30,"Easy",["vegan"],["rolls","fresh","light","healthy"],4,[("rice paper wrappers","12"),("vermicelli noodles","100g"),("shrimp","200g"),("lettuce","1 head"),("carrots","1"),("cucumber","1"),("mint","1 bunch"),("cilantro","1 bunch"),("peanut sauce","for dipping")],["Soak noodles, cook briefly. Boil shrimp.","Soften rice paper in warm water, lay flat.","Layer lettuce, noodles, shrimp, veg, herbs.","Fold sides and roll tightly. Serve with peanut sauce."],180,10,30,4)
add("vn-004","Bun Bo Hue","Vietnamese","vietnamese","Southeast Asian","soup",120,"Hard",[],["soup","noodles","spicy"],4,[("pork hock","500g"),("beef shank","400g"),("lemongrass","4 stalks"),("shrimp paste","2 tbsp"),("annatto oil","2 tbsp"),("chilli oil","2 tbsp"),("rice noodles","400g"),("banana blossom","200g")],["Simmer pork and beef in water with lemongrass.","Add shrimp paste and annatto oil to broth.","Season with fish sauce and sugar.","Serve with thick round noodles, sliced meats, raw herbs."],420,32,40,14)
add("vn-005","Cơm Tấm","Vietnamese","vietnamese","Southeast Asian","rice",60,"Medium",[],["rice","pork","vietnamese"],2,[("broken rice","2 cups"),("pork chop","2"),("egg","2"),("shredded pork skin","100g"),("scallion oil","3 tbsp"),("nuoc cham dipping sauce","4 tbsp"),("cucumber","1")],["Grill marinated pork chops over charcoal until charred.","Fry eggs sunny side up.","Serve broken rice topped with pork, egg, shredded pork skin.","Drizzle scallion oil and nuoc cham."],520,34,54,18)

# ─── INDIAN ───────────────────────────────────────────────────────────────────
add("in-001","Butter Chicken","Indian","indian","South Asian","curry",60,"Medium",[],["curry","creamy","tomato"],4,[("chicken thighs","700g"),("yogurt","150g"),("heavy cream","200ml"),("canned tomatoes","400g"),("butter","3 tbsp"),("garam masala","2 tsp"),("cumin","1 tsp"),("turmeric","½ tsp"),("kasuri methi","1 tbsp"),("garlic","5 cloves"),("ginger","1 inch")],["Marinate chicken in yogurt and spices 1 hr. Grill until charred.","Sauté onions, garlic, ginger. Add spices and tomatoes, simmer 15 min.","Blend sauce smooth, add cream and chicken. Simmer 10 min.","Finish with crushed kasuri methi."],510,42,12,32,"Invented at Moti Mahal, Delhi in the 1950s using leftover tandoori chicken.")
add("in-002","Chicken Biryani","Indian","indian","South Asian","rice",90,"Medium",[],["rice","aromatic","festive"],4,[("basmati rice","2 cups"),("chicken","800g"),("yogurt","200g"),("onions","3 large"),("saffron","pinch"),("whole spices","2 tbsp"),("biryani masala","2 tbsp"),("mint","handful"),("cilantro","handful"),("ghee","3 tbsp")],["Marinate chicken in yogurt and biryani masala overnight.","Fry onions until crispy. Cook rice 80% done.","Layer rice and chicken in pot. Add saffron milk, mint, ghee.","Seal and dum cook (low heat) 25 min."],680,42,78,18,"Dum cooking — sealing the pot and slow-cooking in its own steam — is what makes biryani transcendent.")
add("in-003","Dal Makhani","Indian","indian","South Asian","stew",60,"Medium",["vegetarian"],["lentils","butter","comfort"],4,[("black lentils","1 cup"),("kidney beans","½ cup"),("butter","4 tbsp"),("heavy cream","100ml"),("canned tomatoes","400g"),("garlic","4 cloves"),("ginger","1 tsp"),("cumin seeds","1 tsp"),("garam masala","1 tsp")],["Pressure cook black lentils and kidney beans until soft.","Make tadka: fry cumin in butter, add garlic, ginger, tomatoes.","Add lentils, simmer 30 min stirring often.","Add cream and butter to finish."],420,18,52,16)
add("in-004","Palak Paneer","Indian","indian","South Asian","curry",35,"Easy",["vegetarian"],["spinach","paneer","vegetarian"],3,[("paneer","300g"),("spinach","600g"),("onion","2"),("garlic","4 cloves"),("ginger","1 tsp"),("heavy cream","4 tbsp"),("garam masala","1 tsp"),("cumin","1 tsp"),("turmeric","¼ tsp")],["Blanch spinach 2 min, blend smooth.","Sauté onions until golden. Add garlic, ginger, spices.","Add spinach purée. Simmer 10 min.","Add pan-fried paneer cubes. Finish with cream."],320,18,14,20)
add("in-005","Chicken Tikka Masala","Indian","indian","South Asian","curry",50,"Medium",[],["curry","tomato","cream"],4,[("chicken breast","700g"),("yogurt","150g"),("tikka paste","3 tbsp"),("canned tomatoes","400g"),("heavy cream","150ml"),("onion","2"),("garlic","4 cloves"),("ginger","1 tsp"),("garam masala","1 tsp"),("paprika","1 tsp")],["Marinate chicken in yogurt and tikka paste 2 hr. Grill.","Sauté onion, garlic, ginger. Add tomatoes, simmer 15 min.","Blend sauce, return to pan with cream.","Add grilled chicken. Simmer 10 min."],480,38,18,26)
add("in-006","Chole Bhature","Indian","indian","South Asian","stew",60,"Medium",["vegan-option"],["chickpeas","spiced","punjabi"],4,[("chickpeas","2 cans"),("tomatoes","3"),("onion","2"),("garlic","4 cloves"),("ginger","1 tsp"),("chole masala","2 tbsp"),("pomegranate seeds","1 tbsp"),("bhature (fried bread)","4")],["Sauté onion until dark golden. Add garlic, ginger, tomatoes.","Add chickpeas and masala. Simmer 20 min.","Finish with pomegranate seeds.","Serve with hot bhature bread."],580,18,88,16)
add("in-007","Masala Dosa","Indian","indian","South Asian","eggs",500,"Hard",["vegan","gluten-free"],["crepe","fermented","south indian"],4,[("parboiled rice","2 cups"),("urad dal","½ cup"),("potatoes","4 medium"),("mustard seeds","1 tsp"),("curry leaves","10"),("green chillies","2"),("turmeric","½ tsp"),("onion","1")],["Soak rice and dal 6 hr, grind, ferment 8 hr.","Boil and mash potatoes with mustard, curry leaf, chilli tadka.","Spread thin batter on hot iron griddle.","When golden, add filling, fold and serve with chutneys."],320,9,62,5)
add("in-008","Samosa","Indian","indian","South Asian","stir_fry",60,"Medium",["vegan"],["fried","crispy","snack","street food"],4,[("flour","2 cups"),("potatoes","3 large"),("green peas","½ cup"),("cumin seeds","1 tsp"),("garam masala","1 tsp"),("amchoor powder","½ tsp"),("green chillies","2"),("oil for frying","","")],["Make dough with flour, ghee, water. Rest 30 min.","Cook spiced potato-pea filling.","Shape into cones, fill, seal.","Deep fry at 170°C until golden. Serve with mint chutney."],180,4,24,8)
add("in-009","Saag Aloo","Indian","indian","South Asian","curry",35,"Easy",["vegan"],["potato","spinach","vegetarian"],4,[("potatoes","500g"),("spinach","400g"),("onion","2"),("garlic","3 cloves"),("ginger","1 tsp"),("cumin seeds","1 tsp"),("turmeric","½ tsp"),("garam masala","1 tsp"),("oil","2 tbsp")],["Cube and pan-fry potatoes until golden edges.","Fry cumin in oil, add onion until golden.","Add garlic, ginger, spices, spinach.","Add potatoes, simmer 10 min."],260,8,42,8)
add("in-010","Gulab Jamun","Indian","indian","South Asian","dessert",40,"Medium",["vegetarian"],["dessert","sweet","festive"],8,[("milk powder","2 cups"),("flour","3 tbsp"),("baking soda","¼ tsp"),("ghee","3 tbsp"),("milk","½ cup"),("sugar","2 cups"),("water","1.5 cups"),("cardamom","4 pods"),("rose water","1 tbsp")],["Mix milk powder, flour, baking soda, ghee. Add milk to form soft dough.","Shape into smooth balls. Fry in ghee at 150°C until deep brown.","Make syrup with sugar, water, cardamom, rose water.","Soak warm gulab jamun in warm syrup 30 min."],240,4,42,7)

# ─── ITALIAN ──────────────────────────────────────────────────────────────────
add("it-001","Pasta Carbonara","Italian","italian","Mediterranean","pasta",30,"Medium",[],["pasta","roman","classic"],2,[("spaghetti","200g"),("guanciale","150g"),("egg yolks","4"),("whole egg","1"),("Pecorino Romano","80g"),("Parmigiano","40g"),("black pepper","1 tbsp")],["Cook spaghetti al dente. Reserve 1 cup pasta water.","Render guanciale until crispy.","Whisk yolks with cheese and pepper.","Off heat, toss pasta with guanciale, egg mixture, and pasta water."],680,32,62,32,"No cream — the silky sauce comes purely from emulsified eggs, cheese, and hot pasta water.")
add("it-002","Margherita Pizza","Italian","italian","Mediterranean","pizza",100,"Medium",["vegetarian"],["pizza","neapolitan","classic"],2,[("00 flour","300g"),("yeast","5g"),("San Marzano tomatoes","200g"),("fresh mozzarella","150g"),("fresh basil","handful"),("olive oil","2 tbsp")],["Knead dough and rest 1 hr. Preheat oven maximum with pizza stone.","Crush tomatoes and season with salt and olive oil.","Stretch dough, top with tomatoes and mozzarella.","Bake 6–8 min. Add basil after."],620,24,78,24,"Created in 1889 for Queen Margherita of Savoy — the colours of the Italian flag.")
add("it-003","Risotto ai Funghi","Italian","italian","Mediterranean","rice",35,"Medium",["vegetarian"],["rice","mushroom","creamy"],4,[("Arborio rice","320g"),("porcini mushrooms","30g dried"),("mushrooms","300g fresh"),("white wine","150ml"),("parmesan","80g"),("butter","60g"),("onion","1"),("vegetable stock","1.2L"),("thyme","3 sprigs")],["Soak dried porcini in hot water. Sauté onions in butter.","Add rice, toast 2 min. Add wine and stir until absorbed.","Add warm stock one ladle at a time, stirring constantly.","Finish with soaked porcini, parmesan, and cold butter (mantecatura)."],520,14,72,18)
add("it-004","Osso Buco","Italian","italian","Mediterranean","stew",120,"Medium",[],["veal","braised","milanese"],4,[("veal shanks","4"),("white wine","200ml"),("canned tomatoes","400g"),("onion","2"),("celery","3 stalks"),("carrot","2"),("garlic","4 cloves"),("gremolata (lemon zest + parsley + garlic)","4 tbsp"),("flour","2 tbsp")],["Dust shanks in flour. Brown on all sides.","Sauté veg. Add wine, tomatoes, stock to cover halfway.","Braise at 160°C for 1.5 hr until falling off bone.","Top with gremolata. Serve with saffron risotto."],580,42,18,28)
add("it-005","Tiramisu","Italian","italian","Mediterranean","dessert",30,"Medium",["vegetarian"],["dessert","coffee","no-bake"],8,[("egg yolks","6"),("sugar","150g"),("mascarpone","500g"),("heavy cream","300ml"),("savoiardi biscuits","24"),("espresso","300ml"),("Marsala wine","3 tbsp"),("cocoa powder","for dusting")],["Whisk yolks and sugar until pale. Fold in mascarpone.","Whip cream and fold in.","Dip biscuits briefly in espresso-Marsala.","Layer biscuits and cream. Dust with cocoa. Chill 4 hr."],380,8,34,22)
add("it-006","Amatriciana","Italian","italian","Mediterranean","pasta",25,"Easy",[],["pasta","tomato","guanciale"],4,[("rigatoni or bucatini","400g"),("guanciale","150g"),("San Marzano tomatoes","400g"),("Pecorino Romano","80g"),("dried chilli","1"),("white wine","100ml"),("black pepper","to taste")],["Fry guanciale until crispy. Remove excess fat.","Add chilli. Deglaze with wine.","Add tomatoes, crush and simmer 15 min.","Toss with al dente pasta and Pecorino."],580,22,72,18,"From the mountain town of Amatrice — just four ingredients done perfectly.")
add("it-007","Pesto Genovese","Italian","italian","Mediterranean","pasta",20,"Easy",["vegetarian"],["pasta","basil","liguria"],4,[("pasta","400g"),("fresh basil","80g"),("pine nuts","40g"),("Parmigiano","60g"),("Pecorino","20g"),("garlic","1 clove"),("olive oil","150ml"),("salt","½ tsp")],["Pound basil, garlic, and pine nuts in mortar (or blend).","Add cheeses, then drizzle in olive oil.","Cook pasta al dente. Reserve pasta water.","Toss pasta with pesto, loosening with pasta water."],580,18,72,22)
add("it-008","Lasagna Bolognese","Italian","italian","Mediterranean","pasta",180,"Hard",[],["pasta","beef","comfort","baked"],8,[("lasagna sheets","400g"),("ground beef","500g"),("ground pork","250g"),("carrot","2"),("celery","3 stalks"),("onion","2"),("red wine","200ml"),("canned tomatoes","800g"),("whole milk béchamel","800ml"),("Parmigiano","150g")],["Brown meat, add soffritto veg.","Add wine, then tomatoes. Simmer 2 hr.","Make béchamel with butter, flour, milk.","Layer pasta, ragù, béchamel, Parmigiano. Bake 45 min at 180°C."],720,38,64,32)

# ─── FRENCH ───────────────────────────────────────────────────────────────────
add("fr-001","Coq au Vin","French","french","European","stew",120,"Medium",[],["braised","wine","classic"],4,[("chicken pieces","1.2kg"),("red wine","500ml"),("lardons","150g"),("pearl onions","200g"),("mushrooms","250g"),("garlic","4 cloves"),("thyme","3 sprigs"),("bay leaves","2"),("flour","2 tbsp"),("butter","2 tbsp")],["Brown chicken. Render lardons.","Add wine, stock, garlic, herbs. Braise 45 min.","Add mushrooms and pearl onions. Cook 15 min more.","Reduce sauce to coat. Serve with crusty bread."],520,46,14,24,"Julia Child's favourite recipe for introducing Americans to French home cooking.")
add("fr-002","Bouillabaisse","French","french","European","soup",90,"Hard",[],["soup","seafood","marseille"],6,[("mixed fish","1kg"),("mussels","500g"),("prawns","300g"),("tomatoes","4"),("onion","2"),("fennel","1 bulb"),("garlic","6 cloves"),("saffron","pinch"),("rouille","for serving"),("baguette","1")],["Make soffrito with onion, fennel, garlic, tomatoes.","Add saffron and 1.5L water. Simmer 30 min.","Add fish in order of cooking time. Simmer 15 min.","Serve with rouille-spread baguette croutons."],380,32,18,16)
add("fr-003","Bœuf Bourguignon","French","french","European","stew",180,"Medium",[],["beef","braised","burgundy"],6,[("beef chuck","1.2kg"),("Burgundy wine","750ml"),("lardons","200g"),("pearl onions","200g"),("mushrooms","300g"),("carrot","3"),("garlic","4 cloves"),("thyme","4 sprigs"),("flour","2 tbsp")],["Marinate beef in wine overnight. Brown in batches.","Cook with wine, stock, vegetables 2 hr at 160°C.","Add mushrooms and onions last 30 min.","Reduce sauce, season. Classic winter dish."],580,42,18,28)
add("fr-004","Crème Brûlée","French","french","European","dessert",60,"Medium",["vegetarian"],["dessert","custard","vanilla"],4,[("heavy cream","500ml"),("egg yolks","5"),("sugar","100g"),("vanilla bean","1"),("extra sugar","4 tbsp for topping")],["Infuse cream with vanilla. Whisk yolks with sugar.","Strain cream into yolks, pour into ramekins.","Bake in water bath 40 min at 160°C.","Chill, then torch sugar until caramelised."],380,4,28,28)
add("fr-005","Ratatouille","French","french","European","stew",60,"Medium",["vegan"],["vegetable","provence","summer"],4,[("eggplant","1"),("zucchini","2"),("red peppers","2"),("tomatoes","4"),("onion","2"),("garlic","4 cloves"),("herbes de Provence","2 tsp"),("olive oil","4 tbsp")],["Roast each vegetable separately in olive oil.","Sauté onion and garlic. Add tomatoes, cook 10 min.","Combine all vegetables with herbs. Simmer 20 min.","Serve warm or at room temperature."],180,4,24,9)
add("fr-006","Croissant","French","french","European","bread",480,"Hard",["vegetarian"],["pastry","breakfast","butter"],8,[("flour","500g"),("butter","250g cold"),("milk","300ml"),("yeast","10g"),("sugar","2 tbsp"),("salt","10g"),("egg for egg wash","1")],["Make dough and chill 1 hr. Laminate with cold butter in 3 folds.","Rest 30 min between each fold (3 total).","Shape into crescents, proof 3 hr.","Egg wash and bake at 200°C for 15-18 min."],320,6,36,18)
add("fr-007","French Onion Soup","French","french","European","soup",60,"Medium",["vegetarian-option"],["soup","onion","gratin"],4,[("onions","1kg"),("butter","60g"),("white wine","200ml"),("beef stock","1L"),("Gruyère","150g"),("baguette slices","4"),("thyme","3 sprigs"),("bay leaves","2")],["Caramelise onions in butter over low heat 45 min until deep golden.","Add wine, reduce. Add stock and herbs, simmer 20 min.","Ladle into oven-proof bowls.","Top with baguette, pile on Gruyère, broil until bubbly."],380,12,32,20)

# ─── MEXICAN ──────────────────────────────────────────────────────────────────
add("mx-001","Tacos al Pastor","Mexican","mexican","Latin American","tacos",80,"Medium",[],["tacos","pork","street food"],6,[("pork shoulder","1kg"),("dried guajillo chillies","4"),("dried ancho chillies","2"),("pineapple","½"),("achiote paste","2 tbsp"),("corn tortillas","18"),("onion","1"),("cilantro","1 bunch"),("lime","2")],["Blend chillies with achiote into paste. Marinate pork 1 hr.","Grill on high heat until charred.","Warm tortillas. Layer pork, grilled pineapple, onion, cilantro.","Serve with lime."],380,28,34,14,"Lebanese immigrants introduced spit-roasted shawarma in the 1930s — Mexicans made it their own.")
add("mx-002","Mole Negro","Mexican","mexican","Latin American","curry",240,"Hard",[],["chocolate","complex","oaxacan","festive"],8,[("chicken","1.5kg"),("dried mulato chillies","5"),("dried ancho chillies","4"),("dark chocolate","60g"),("onion","2"),("tomatoes","3"),("garlic","6 cloves"),("almonds","50g"),("sesame seeds","3 tbsp"),("plantain","1"),("spices","2 tbsp")],["Char then soak all dried chillies.","Fry each ingredient separately: tomatoes, onion, garlic, nuts.","Blend everything in stages.","Simmer mole with chicken stock and chocolate 1 hr. Adjust seasoning."],480,32,28,24,"Over 20 ingredients, 3 days traditionally — Mexico's most complex sauce.")
add("mx-003","Chiles Rellenos","Mexican","mexican","Latin American","eggs",60,"Hard",["vegetarian"],["stuffed peppers","cheese","battered"],4,[("poblano peppers","4"),("Oaxacan cheese","300g"),("eggs","4"),("flour","4 tbsp"),("tomatoes","3"),("garlic","3 cloves"),("oil for frying","","")],["Char peppers over flame, peel, make slit. Remove seeds.","Stuff with cheese. Dredge in flour.","Beat egg whites to stiff peaks, fold in yolks.","Coat peppers in egg batter, fry until golden. Serve in tomato sauce."],380,18,24,22)
add("mx-004","Pozole Rojo","Mexican","mexican","Latin American","soup",180,"Medium",[],["soup","hominy","pork","festive"],8,[("pork shoulder","800g"),("hominy","400g"),("dried guajillo chillies","5"),("dried ancho chillies","3"),("garlic","6 cloves"),("oregano","2 tsp"),("tostadas","8"),("cabbage","½ head"),("radishes","8"),("lime","4")],["Simmer pork until tender, shred.","Blend soaked chillies with garlic, strain into broth.","Add hominy, simmer 30 min.","Serve topped with cabbage, radishes, oregano, and lime."],380,28,42,12)
add("mx-005","Guacamole","Mexican","mexican","Latin American","salad",10,"Easy",["vegan","gluten-free"],["avocado","dip","quick"],4,[("ripe avocados","3"),("lime juice","2 tbsp"),("white onion","½"),("serrano chilli","1"),("cilantro","handful"),("tomato","1"),("salt","to taste")],["Mash avocados to desired consistency.","Fold in diced onion, chilli, cilantro, tomato.","Season with lime juice and salt.","Serve immediately with tortilla chips."],180,2,12,16)
add("mx-006","Enchiladas Verdes","Mexican","mexican","Latin American","stew",50,"Medium",["vegetarian"],["chicken","salsa verde","baked"],4,[("corn tortillas","12"),("chicken breast","400g"),("tomatillos","500g"),("jalapeños","3"),("onion","1"),("garlic","3 cloves"),("cream","100ml"),("queso fresco","150g"),("cilantro","handful")],["Poach chicken, shred.","Blend charred tomatillos, jalapeños, onion, garlic for salsa verde.","Simmer salsa 10 min. Dip tortillas briefly.","Roll tortillas around chicken, top with sauce and cream. Bake 15 min."],420,28,48,14)
add("mx-007","Carnitas","Mexican","mexican","Latin American","stew",120,"Easy",[],["pork","braised","taco filling"],8,[("pork shoulder","1.5kg"),("orange juice","½ cup"),("lime juice","3 tbsp"),("garlic","6 cloves"),("cumin","2 tsp"),("oregano","1 tsp"),("lard or oil","3 tbsp")],["Brown pork pieces in lard.","Add orange juice, lime, garlic, spices and water to cover halfway.","Braise uncovered 1 hr until liquid evaporates.","Shred and crisp meat in its own fat. Serve in tacos."],480,34,6,32)

# ─── GREEK ────────────────────────────────────────────────────────────────────
add("gr-001","Moussaka","Greek","greek","Mediterranean","stew",90,"Medium",[],["eggplant","béchamel","baked"],6,[("eggplant","2 large"),("ground lamb","500g"),("onion","2"),("canned tomatoes","400g"),("cinnamon","1 tsp"),("allspice","½ tsp"),("béchamel sauce","600ml"),("Kefalotyri cheese","80g"),("olive oil","4 tbsp")],["Slice and salt eggplant, fry until golden.","Brown lamb with onion, spices, tomatoes.","Layer eggplant and meat sauce in baking dish.","Top with béchamel, cheese. Bake 45 min at 180°C."],580,28,32,34)
add("gr-002","Souvlaki","Greek","greek","Mediterranean","grilled",30,"Easy",[],["grilled","pork","street food"],4,[("pork shoulder","600g"),("olive oil","3 tbsp"),("lemon juice","2 tbsp"),("oregano","1 tbsp"),("garlic","3 cloves"),("pita breads","4"),("tzatziki","200ml"),("tomatoes","2"),("red onion","1"),("paprika","1 tsp")],["Cube pork. Marinate in olive oil, lemon, oregano, garlic 2 hr.","Thread onto skewers. Grill 3–4 min each side.","Warm pita. Top with souvlaki, tomato, onion, paprika.","Serve with tzatziki."],480,32,38,18)
add("gr-003","Spanakopita","Greek","greek","Mediterranean","bread",75,"Medium",["vegetarian"],["spinach","feta","phyllo","pastry"],8,[("fresh spinach","800g"),("feta cheese","300g"),("phyllo pastry","250g"),("eggs","2"),("onion","1"),("scallions","4"),("dill","small bunch"),("butter melted","50g"),("olive oil","100ml")],["Wilt spinach, squeeze very dry, chop.","Mix with crumbled feta, sautéed onion, eggs, dill.","Layer 5 phyllo sheets (brushing each with butter) in baking dish.","Spread filling, top with 5 more sheets. Score and bake at 180°C 45 min."],320,12,28,18)
add("gr-004","Tzatziki","Greek","greek","Mediterranean","salad",15,"Easy",["vegetarian","gluten-free"],["dip","yogurt","cucumber"],8,[("Greek yogurt","400g"),("cucumber","1 large"),("garlic","2 cloves"),("fresh dill","2 tbsp"),("olive oil","2 tbsp"),("lemon juice","1 tbsp"),("salt","½ tsp")],["Grate cucumber and squeeze out all moisture.","Mix yogurt with garlic, dill, olive oil, lemon.","Fold in cucumber.","Chill 1 hr. Serve with pita."],80,4,6,4)
add("gr-005","Baklava","Greek","greek","Mediterranean","dessert",90,"Hard",["vegetarian"],["dessert","nuts","honey","pastry"],16,[("phyllo pastry","500g"),("walnuts","400g"),("pistachios","100g"),("butter melted","200g"),("honey","200ml"),("sugar","150g"),("water","100ml"),("cinnamon","2 tsp"),("cloves","4")],["Finely chop nuts with cinnamon.","Layer phyllo in buttered pan, add nut layer, repeat.","Cut into diamonds before baking at 160°C for 45 min.","Pour hot sugar-honey syrup over hot baklava."],280,4,36,14)

# ─── MOROCCAN ─────────────────────────────────────────────────────────────────
add("ma-001","Lamb Tagine","Moroccan","moroccan","Mediterranean","stew",150,"Medium",[],["tagine","lamb","dried fruit"],4,[("lamb shoulder","800g"),("dried apricots","150g"),("prunes","100g"),("onion","2"),("garlic","4 cloves"),("ras el hanout","2 tsp"),("cinnamon","1 stick"),("saffron","pinch"),("honey","2 tbsp"),("almonds","50g")],["Brown lamb. Slow-fry onion until soft.","Add garlic, ras el hanout, cinnamon, saffron.","Add dried fruit, enough water to cover, and honey.","Simmer covered 1.5 hr. Top with almonds."],560,42,32,28)
add("ma-002","Chicken Bastilla","Moroccan","moroccan","Mediterranean","bread",120,"Hard",[],["pastry","chicken","almonds","festive"],8,[("chicken","1kg"),("onion","2"),("eggs","3"),("almonds","200g"),("cinnamon","2 tsp"),("ras el hanout","1 tsp"),("saffron","pinch"),("warqa pastry (or phyllo)","500g"),("honey","2 tbsp"),("icing sugar","for dusting")],["Braise chicken with onion, saffron, spices until very tender. Shred.","Make almond filling with ground almonds, cinnamon, sugar.","Layer pastry with chicken, scrambled eggs, then almond layer.","Fold pastry over, bake at 180°C. Dust with cinnamon and icing sugar."],480,32,42,22,"The sweet-savoury union defines Moroccan Moorish cooking — sugar and cinnamon on a meat pie.")
add("ma-003","Harira","Moroccan","moroccan","Mediterranean","soup",60,"Medium",["vegan-option"],["soup","lentils","ramadan"],6,[("canned tomatoes","400g"),("chickpeas","1 can"),("green lentils","1 cup"),("celery","3 stalks"),("onion","2"),("cilantro","1 bunch"),("parsley","1 bunch"),("turmeric","1 tsp"),("cinnamon","½ tsp"),("vermicelli","80g"),("lemon","2")],["Sauté onion and celery. Add spices and tomatoes.","Add lentils, chickpeas, and 2L water.","Simmer 30 min. Add vermicelli and herbs.","Season with lemon. Serve with dates and chebakia."],220,10,32,3)
add("ma-004","Couscous Tfaya","Moroccan","moroccan","Mediterranean","rice",60,"Medium",["vegetarian"],["couscous","caramelised onion","sweet"],4,[("couscous","400g"),("onions","4 large"),("raisins","100g"),("chickpeas","1 can"),("ras el hanout","1 tsp"),("cinnamon","1 tsp"),("saffron","pinch"),("butter","60g"),("honey","2 tbsp"),("almonds","50g")],["Steam couscous twice with butter between. Fluff with fork.","Caramelise onions in butter 40 min. Add raisins, cinnamon, honey.","Warm chickpeas separately.","Serve couscous topped with tfaya and chickpeas."],480,10,82,14)

# ─── ETHIOPIAN ────────────────────────────────────────────────────────────────
add("et-001","Doro Wat","Ethiopian","ethiopian","African","curry",120,"Hard",[],["chicken","berbere","injera","stew"],4,[("chicken pieces","1kg"),("onion","4 large"),("berbere spice","3 tbsp"),("niter kibbeh","4 tbsp"),("garlic","6 cloves"),("ginger","1 tbsp"),("hard-boiled eggs","4"),("red wine","100ml")],["Caramelise onions in niter kibbeh 30–40 min until very dark.","Add garlic, ginger, berbere. Fry 5 min.","Add chicken and wine. Braise 45 min.","Add pierced eggs. Serve on injera."],480,44,12,28,"The queen of Ethiopian cuisine — slow-caramelised onions without fat is the signature technique.")
add("et-002","Misir Wot","Ethiopian","ethiopian","African","stew",40,"Easy",["vegan","gluten-free"],["lentils","berbere","red","vegan"],4,[("red lentils","1.5 cups"),("onion","2"),("berbere spice","2 tbsp"),("niter kibbeh or oil","3 tbsp"),("garlic","4 cloves"),("ginger","1 tsp"),("tomatoes","2")],["Fry onion in niter kibbeh until dark golden.","Add garlic, ginger, berbere. Stir 2 min.","Add lentils and 2 cups water. Simmer 20 min until very thick.","Serve on injera with other wots."],280,14,38,8)
add("et-003","Tibs","Ethiopian","ethiopian","African","stir_fry",25,"Easy",[],["beef","stir-fried","spiced"],4,[("beef sirloin","600g"),("red onion","2"),("jalapeños","3"),("rosemary","2 sprigs"),("niter kibbeh","3 tbsp"),("garlic","3 cloves"),("berbere","1 tsp"),("lime juice","1 tbsp")],["Melt niter kibbeh in pan until very hot.","Sear beef in batches until nicely browned.","Add onion, garlic, jalapeños, rosemary, berbere.","Toss 3 min. Finish with lime."],320,30,8,18)

# ─── NIGERIAN ─────────────────────────────────────────────────────────────────
add("ng-001","Jollof Rice","Nigerian","nigerian","African","rice",65,"Medium",[],["rice","tomato","party"],6,[("long-grain rice","400g"),("plum tomatoes","4"),("red bell peppers","2"),("scotch bonnet","1"),("onion","2 large"),("tomato paste","2 tbsp"),("chicken stock","500ml"),("vegetable oil","100ml"),("thyme","1 tsp"),("seasoning cubes","2")],["Blend tomatoes, peppers, scotch bonnet. Fry in oil with tomato paste.","Slice and fry remaining onion. Combine with pepper base.","Add stock, spices, and washed rice. Cover tightly.","Cook 20 min medium, then 15 min low. For smoky base, flash on high."],380,8,68,9,"The Jollof Wars — Nigeria vs Ghana vs Senegal. The smoky bottom (party jollof) is Nigeria's secret.")
add("ng-002","Egusi Soup","Nigerian","nigerian","African","stew",60,"Medium",[],["egusi","palm oil","stew","greens"],4,[("egusi seeds","200g"),("palm oil","100ml"),("stockfish","100g"),("crayfish","2 tbsp"),("spinach or bitter leaf","200g"),("stockfish and beef","400g combined"),("locust beans","1 tbsp"),("scotch bonnet","2"),("onion","2")],["Fry egusi paste in hot palm oil 15 min until separated.","Add stock, crayfish, locust beans, stockfish.","Simmer 20 min. Add greens and meat.","Season with salt and scotch bonnet."],380,24,12,26)
add("ng-003","Suya","Nigerian","nigerian","African","grilled",45,"Easy",[],["beef","spiced","street food","skewers"],4,[("beef sirloin","600g"),("yaji spice mix","4 tbsp"),("groundnut oil","3 tbsp"),("garlic powder","1 tsp"),("ginger powder","1 tsp"),("onion","1 for serving"),("tomatoes","2 for serving")],["Slice beef into thin strips against grain.","Rub with yaji, garlic, ginger, oil.","Skewer and grill over hot charcoal, basting with oil.","Serve with raw onion, tomatoes, and extra yaji."],320,28,8,18)

# ─── PERUVIAN ─────────────────────────────────────────────────────────────────
add("pe-001","Ceviche Clásico","Peruvian","peruvian","Latin American","seafood",20,"Easy",["gluten-free"],["seafood","citrus","raw","light"],4,[("sea bass or flounder","500g"),("lime juice","200ml"),("ají amarillo paste","2 tsp"),("red onion","1"),("cilantro","handful"),("corn on the cob","1"),("sweet potato","1 boiled")],["Cube fish. Salt and rest 5 min.","Add lime juice and ají amarillo. Cure 5–10 min.","Add red onion and cilantro.","Serve with choclo and sweet potato."],180,28,12,3,"Peru's national dish — the leche de tigre (tiger's milk) leftover juice is drunk straight as a hangover cure.")
add("pe-002","Lomo Saltado","Peruvian","peruvian","Latin American","stir_fry",25,"Medium",[],["beef","stir-fry","chifa","fusion"],4,[("beef sirloin","500g"),("tomatoes","2"),("red onion","2"),("yellow peppers","2"),("ají amarillo","2"),("soy sauce","3 tbsp"),("oyster sauce","1 tbsp"),("cilantro","handful"),("fries","for serving"),("rice","for serving")],["Cut beef into strips. Sear in very hot wok until charred.","Add onion, peppers, ají amarillo. Stir-fry 2 min.","Add tomatoes, soy sauce, oyster sauce.","Serve immediately over rice and fries. Top with cilantro."],580,32,58,18,"The meeting of Peru and China — Chinese immigrants brought wok technique; the Peruvians added ají amarillo.")
add("pe-003","Anticuchos","Peruvian","peruvian","Latin American","grilled",40,"Easy",[],["grilled","beef heart","street food"],4,[("beef heart","600g"),("dried ají panca paste","3 tbsp"),("garlic","4 cloves"),("cumin","1 tsp"),("red wine vinegar","2 tbsp"),("soy sauce","1 tbsp"),("corn on the cob","2"),("potato","4")],["Clean and cube beef heart. Marinate in ají panca, garlic, cumin, vinegar overnight.","Thread onto skewers.","Grill over hot coals 3–4 min each side, basting with marinade.","Serve with grilled corn and boiled potato."],280,26,14,12)

# ─── BRAZILIAN ────────────────────────────────────────────────────────────────
add("br-001","Feijoada","Brazilian","brazilian","Latin American","stew",240,"Hard",[],["black beans","pork","slow cook","national dish"],8,[("dried black beans","500g"),("pork ribs","400g"),("smoked sausage","200g"),("bacon","150g"),("pork trotter","200g"),("onion","2"),("garlic","6 cloves"),("bay leaves","3"),("orange","for serving")],["Soak beans overnight.","Braise cured meats 1 hr separately.","Combine all with beans and seasonings. Simmer 2–3 hr.","Mash some beans for thickness. Serve with rice, farofa, orange."],640,48,52,22)
add("br-002","Churrasco","Brazilian","brazilian","Latin American","grilled",60,"Easy",[],["bbq","beef","picanha","festive"],6,[("picanha (rump cap)","1kg"),("coarse sea salt","3 tbsp"),("garlic","4 cloves"),("chimichurri","for serving")],["Score fat cap in diamond pattern.","Rub generously with coarse salt (the only seasoning needed).","Skewer in a curve, fat side out. Grill over hot coals 30 min.","Rest 10 min. Slice thin against grain."],520,42,0,38)
add("br-003","Moqueca","Brazilian","brazilian","Latin American","stew",45,"Medium",["gluten-free"],["fish","coconut","bahian"],4,[("firm white fish","600g"),("coconut milk","400ml"),("dendê (palm oil)","3 tbsp"),("tomatoes","3"),("red peppers","2"),("onion","2"),("garlic","4 cloves"),("cilantro","handful"),("lime","2")],["Marinate fish in lime, garlic, salt.","Sauté onion, garlic, tomatoes, peppers in dendê.","Add coconut milk and fish. Simmer 15 min without stirring.","Top with cilantro. Serve with white rice and farofa."],380,32,16,22)

# ─── JAMAICAN ─────────────────────────────────────────────────────────────────
add("jm-001","Jerk Chicken","Jamaican","jamaican","Caribbean","grilled",525,"Medium",[],["grilled","spicy","island","bbq"],4,[("whole chicken","1.5kg"),("scotch bonnet","3"),("allspice","2 tbsp"),("thyme","4 sprigs"),("garlic","4 cloves"),("scallions","4"),("soy sauce","2 tbsp"),("brown sugar","1 tbsp"),("nutmeg","¼ tsp"),("ginger","1 inch")],["Blend all marinade ingredients. Score and coat chicken.","Marinate overnight.","Grill indirect heat 180°C 30 min, then direct 15 min.","Rest 10 min. Serve with rice and peas, festival."],480,52,8,26,"Born with the Maroons cooking over pimento (allspice) wood in Jamaica's Blue Mountains.")
add("jm-002","Ackee and Saltfish","Jamaican","jamaican","Caribbean","eggs",40,"Easy",[],["breakfast","national dish","saltfish"],4,[("salt cod","300g"),("canned ackee","540g"),("onion","2"),("scotch bonnet","1"),("tomatoes","2"),("scallions","4"),("thyme","3 sprigs"),("oil","2 tbsp"),("escallion","3")],["Desalt cod overnight in cold water. Boil and flake.","Sauté onion, pepper, tomatoes, thyme.","Add cod and ackee, fold gently.","Serve with fried dumplings, breadfruit, or rice."],280,22,14,14)
add("jm-003","Oxtail Stew","Jamaican","jamaican","Caribbean","stew",180,"Hard",[],["oxtail","slow cook","comfort"],4,[("oxtail","1.2kg"),("broad beans","1 can"),("onion","2"),("scotch bonnet","1"),("garlic","4 cloves"),("thyme","4 sprigs"),("allspice","1 tsp"),("soy sauce","3 tbsp"),("Worcestershire sauce","2 tbsp"),("butter beans","1 can")],["Season oxtail. Brown in batches.","Add all aromatics and just enough water to cover.","Pressure cook 1.5 hr or slow cook 4 hr.","Add butter beans last 20 min. Serve with rice and peas."],580,38,28,32)

# ─── AMERICAN ─────────────────────────────────────────────────────────────────
add("us-001","Smash Burger","American","american","North American","burger",20,"Easy",[],["burger","beef","quick"],2,[("80/20 ground beef","400g"),("American cheese","4 slices"),("brioche buns","2"),("white onion grated","½"),("pickles","6 slices"),("smash sauce","4 tbsp")],["Roll beef into 100g balls. Season.","Heat cast iron until smoking. Smash balls flat immediately.","Cook 2 min, flip, add cheese.","Toast buns in beef fat. Assemble with sauce, onion, pickles."],720,46,38,42,"Smashing creates maximum Maillard crust — way more flavour than a fat patty.")
add("us-002","BBQ Brisket","American","american","North American","grilled",480,"Hard",[],["bbq","beef","smoke","texas"],8,[("beef brisket","3kg"),("salt","3 tbsp"),("black pepper","2 tbsp"),("garlic powder","1 tbsp"),("oak wood chips","handful")],["Trim brisket, leaving ¼ inch fat cap. Apply salt-pepper-garlic rub.","Smoke at 107°C for 8–12 hr until internal temp 95°C.","Wrap in butcher paper when bark sets (after ~6 hr).","Rest 2 hr before slicing."],420,38,2,28,"Texas BBQ gospel: salt + pepper + time + smoke. Nothing else.")
add("us-003","Clam Chowder","American","american","North American","soup",40,"Medium",[],["soup","clams","new england","creamy"],4,[("clams","1kg"),("potatoes","400g"),("bacon","150g"),("onion","2"),("celery","3 stalks"),("heavy cream","300ml"),("flour","2 tbsp"),("butter","2 tbsp"),("thyme","3 sprigs"),("bay leaves","2")],["Steam clams, reserve liquor.","Fry bacon, sauté veg. Add flour, clam liquor, potatoes.","Simmer 15 min until potatoes tender.","Add cream, clams, season."],380,18,32,22)
add("us-004","Mac and Cheese","American","american","North American","pasta",30,"Easy",["vegetarian"],["pasta","cheese","comfort","southern"],6,[("macaroni","400g"),("Cheddar","300g"),("Gruyère","100g"),("butter","4 tbsp"),("flour","3 tbsp"),("milk","600ml"),("mustard","1 tsp"),("hot sauce","1 tsp"),("breadcrumbs","100g")],["Make béchamel with butter, flour, milk. Add cheeses.","Cook macaroni al dente.","Combine macaroni and sauce in baking dish.","Top with breadcrumbs and extra cheese. Bake 20 min at 200°C."],620,24,72,26)
add("us-005","Buffalo Wings","American","american","North American","grilled",50,"Easy",[],["chicken","spicy","bar food"],4,[("chicken wings","1kg"),("hot sauce","100ml"),("butter","60g"),("garlic powder","1 tsp"),("oil","for frying",""),("blue cheese dip","for serving")],["Deep fry wings at 180°C for 10–12 min.","Make sauce: simmer hot sauce with butter and garlic powder.","Toss wings in sauce until coated.","Serve with blue cheese dip and celery sticks."],480,32,8,32)
add("us-006","Pulled Pork","American","american","North American","stew",360,"Hard",[],["pork","bbq","slow cook","southern"],8,[("pork shoulder","2kg"),("apple cider vinegar","100ml"),("brown sugar","2 tbsp"),("paprika","2 tbsp"),("cumin","1 tsp"),("garlic powder","1 tsp"),("mustard","1 tbsp"),("BBQ sauce","200ml"),("brioche buns","8")],["Make dry rub. Coat pork generously.","Slow cook at 120°C for 6 hr or until internal temp 90°C.","Shred with two forks.","Toss in BBQ sauce. Pile onto buns with slaw."],580,34,48,22)
add("us-007","Fried Chicken","American","american","North American","grilled",60,"Medium",[],["chicken","crispy","southern"],4,[("chicken pieces","1.2kg"),("buttermilk","500ml"),("flour","2 cups"),("paprika","2 tsp"),("garlic powder","1 tsp"),("cayenne","½ tsp"),("salt","2 tsp"),("oil","for frying","")],["Soak chicken in buttermilk overnight.","Mix flour with spices. Dredge chicken, shake off excess.","Fry at 160°C for 12–15 min until golden and cooked through.","Drain on rack. Season immediately."],580,38,42,26)

# ─── CAJUN ────────────────────────────────────────────────────────────────────
add("cj-001","Chicken Gumbo","Cajun","cajun","North American","stew",90,"Hard",[],["gumbo","roux","louisiana","bayou"],6,[("chicken","1kg"),("andouille sausage","300g"),("okra","300g"),("onion","2"),("celery","3 stalks"),("bell pepper","2"),("flour","4 tbsp"),("vegetable oil","4 tbsp"),("chicken stock","1.5L"),("filé powder","1 tsp")],["Make dark roux: cook flour in oil over medium heat, stirring constantly 30 min.","Add trinity (onion, celery, pepper). Cook 10 min.","Add stock, chicken, sausage, okra. Simmer 45 min.","Season with filé, salt, and Cajun spices. Serve over rice."],480,34,28,24,"A dark roux is the soul of gumbo — cook it until it smells like chocolate, not raw flour.")
add("cj-002","Jambalaya","Cajun","cajun","North American","rice",60,"Medium",[],["rice","one-pot","shrimp","sausage"],6,[("andouille sausage","300g"),("shrimp","300g"),("chicken","400g"),("long-grain rice","2 cups"),("onion","2"),("celery","3 stalks"),("bell pepper","2"),("canned tomatoes","400g"),("chicken stock","500ml"),("Cajun seasoning","2 tbsp")],["Brown sausage and chicken. Sauté trinity.","Add tomatoes, stock, Cajun seasoning, and rice.","Cover and cook 20 min without lifting lid.","Add shrimp last 5 min. Fluff with fork."],520,32,52,18)

# ─── SPANISH ──────────────────────────────────────────────────────────────────
add("es-001","Paella Valenciana","Spanish","spanish","Mediterranean","rice",60,"Medium",[],["rice","saffron","rabbit","traditional"],6,[("bomba rice","400g"),("rabbit","600g"),("chicken","600g"),("runner beans","200g"),("tomatoes","2"),("saffron","generous pinch"),("pimentón","1 tsp"),("chicken stock","1.2L"),("olive oil","4 tbsp"),("rosemary","2 sprigs")],["Brown rabbit and chicken. Set aside.","Sauté tomato, pimentón. Add meat back.","Add stock and saffron, bring to boil.","Add rice in cross pattern. Cook 18 min without stirring. Rest 5 min."],520,34,58,16,"True Valencian paella has rabbit and chicken — no seafood. The socarrat (crispy bottom) is the prize.")
add("es-002","Gazpacho","Spanish","spanish","Mediterranean","salad",20,"Easy",["vegan","gluten-free"],["soup","cold","summer"],4,[("vine tomatoes","800g"),("cucumber","½"),("red pepper","1"),("garlic","2 cloves"),("sherry vinegar","2 tbsp"),("olive oil","80ml"),("stale bread","2 slices"),("salt","1 tsp")],["Soak bread briefly in water.","Blend all vegetables, bread, vinegar, oil until smooth.","Season and chill at least 2 hr.","Serve with diced veg garnish and drizzle of olive oil."],160,3,20,9)
add("es-003","Tortilla Española","Spanish","spanish","Mediterranean","eggs",30,"Medium",["vegetarian"],["egg","potato","tapa"],6,[("potatoes","600g"),("eggs","6"),("onion","2"),("olive oil","200ml"),("salt","1.5 tsp")],["Slowly fry potato and onion in olive oil 20 min until tender.","Beat eggs, add drained potato-onion mixture.","Cook in 9-inch pan over medium heat until sides set.","Flip and cook other side. Should be custardy inside."],280,10,28,16)
add("es-004","Patatas Bravas","Spanish","spanish","Mediterranean","stew",40,"Easy",["vegan"],["potato","tapas","spicy"],4,[("potatoes","600g"),("olive oil","100ml"),("tomatoes","3"),("garlic","3 cloves"),("paprika","2 tsp"),("cayenne","¼ tsp"),("white wine vinegar","1 tbsp"),("mayo","for serving")],["Cube potatoes. Fry in olive oil at 160°C until cooked.","Increase heat to 190°C. Fry again 5 min until crispy.","Make bravas sauce: fry garlic, add tomatoes, paprika, cayenne, vinegar.","Serve chips topped with sauce and mayo."],320,4,38,18)

# ─── LEBANESE ─────────────────────────────────────────────────────────────────
add("lb-001","Hummus","Lebanese","lebanese","Middle Eastern","salad",30,"Easy",["vegan","gluten-free"],["dip","chickpeas","tahini"],8,[("chickpeas","2 cans"),("tahini","4 tbsp"),("lemon juice","3 tbsp"),("garlic","2 cloves"),("ice water","4 tbsp"),("olive oil","for serving"),("paprika","pinch")],["Drain chickpeas, reserve liquid. Peel for smoother hummus.","Blend tahini and lemon juice until white and airy.","Add garlic, chickpeas, ice water. Blend until very smooth.","Serve with olive oil, paprika, warm pita."],180,6,24,8,"The key is blending the tahini first — it lightens the texture before adding chickpeas.")
add("lb-002","Shakshuka","Lebanese","lebanese","Middle Eastern","eggs",35,"Easy",["vegetarian","gluten-free"],["eggs","tomato","spiced","one-pan"],2,[("eggs","4"),("canned tomatoes","400g"),("red peppers","2"),("onion","1"),("garlic","3 cloves"),("cumin","1 tsp"),("paprika","1 tsp"),("cayenne","¼ tsp"),("feta","50g"),("parsley","handful")],["Sauté onion and peppers. Add garlic and spices.","Add tomatoes, simmer 10 min.","Make wells, crack eggs in. Cover 8–10 min.","Top with feta and parsley. Serve with pita."],280,18,18,16)
add("lb-003","Kibbeh","Lebanese","lebanese","Middle Eastern","grilled",60,"Medium",[],["lamb","bulgur","stuffed","baked"],6,[("fine bulgur","1 cup"),("lamb mince","600g"),("onion","2"),("pine nuts","50g"),("allspice","1 tsp"),("cinnamon","½ tsp"),("mint","2 tbsp"),("olive oil","3 tbsp")],["Mix bulgur with lamb, onion, allspice, mint for shell.","Make filling: brown lamb with onion, pine nuts, cinnamon.","Form oval shells, stuff with filling.","Bake at 180°C 25 min, or fry until golden."],380,22,28,18)
add("lb-004","Tabbouleh","Lebanese","lebanese","Middle Eastern","salad",20,"Easy",["vegan","gluten-free-option"],["salad","parsley","bulgur"],4,[("flat-leaf parsley","2 large bunches"),("bulgur","50g"),("mint","small bunch"),("tomatoes","3"),("scallions","4"),("lemon juice","3 tbsp"),("olive oil","3 tbsp"),("salt","½ tsp")],["Soak bulgur in cold water 20 min. Drain well.","Finely chop parsley, mint, scallions, tomatoes.","Mix all together.","Season with lemon, olive oil, salt. Parsley is the hero — not the bulgur."],140,3,18,7)

# ─── TURKISH ──────────────────────────────────────────────────────────────────
add("tr-001","Adana Kebab","Turkish","turkish","Middle Eastern","grilled",40,"Medium",[],["lamb","grilled","spicy","kebab"],4,[("lamb mince","600g"),("tail fat","80g"),("red pepper flakes","2 tbsp"),("isot pepper","1 tbsp"),("garlic","3 cloves"),("salt","1½ tsp"),("flatbreads","4")],["Knead lamb with fat, peppers, garlic, salt until sticky.","Shape onto wide flat skewers.","Grill over charcoal 4–5 min each side.","Serve over flatbread with sumac onions and tomatoes."],420,30,24,24)
add("tr-002","Manti","Turkish","turkish","Middle Eastern","noodles",90,"Hard",[],["dumplings","lamb","yogurt"],4,[("flour","2 cups"),("egg","1"),("water","4 tbsp"),("lamb mince","200g"),("onion","1 grated"),("black pepper","½ tsp"),("yogurt","400g"),("garlic","3 cloves"),("butter","3 tbsp"),("paprika","1 tsp")],["Make stiff dough. Roll very thin. Cut into 3cm squares.","Place small amount of lamb filling, pinch corners together.","Boil dumplings 5 min.","Serve with garlic yogurt, browned paprika butter."],480,18,58,18)
add("tr-003","Baklava","Turkish","turkish","Middle Eastern","dessert",90,"Hard",["vegetarian"],["pastry","pistachios","honey","sweet"],20,[("phyllo pastry","500g"),("pistachios","400g"),("butter melted","200g"),("sugar","300g"),("water","200ml"),("honey","2 tbsp"),("lemon juice","1 tbsp"),("rose water","1 tsp")],["Butter each phyllo layer. After 8 layers, add nut layer.","Continue alternating. Cut into diamonds before baking.","Bake at 160°C for 45 min until golden.","Pour cool syrup over hot baklava. Rest 4 hr."],280,3,36,14)
add("tr-004","Menemen","Turkish","turkish","Middle Eastern","eggs",20,"Easy",["vegetarian"],["eggs","tomato","pepper","breakfast"],2,[("eggs","4"),("tomatoes","2"),("green peppers","2"),("onion","1"),("olive oil","2 tbsp"),("red pepper flakes","½ tsp"),("white cheese","50g")],["Sauté onion and green peppers in olive oil.","Add chopped tomatoes and chilli, cook 5 min.","Add beaten eggs, stir gently.","Serve soft-scrambled with white cheese and crusty bread."],280,16,14,16)

# ─── PERSIAN ──────────────────────────────────────────────────────────────────
add("ir-001","Ghormeh Sabzi","Persian","persian","Middle Eastern","stew",180,"Medium",[],["herb stew","lamb","dried limes","aromatic"],4,[("lamb shoulder","600g"),("dried fenugreek","2 tbsp"),("parsley","1 bunch"),("spinach","200g"),("dried kidney beans","200g"),("dried limes","3"),("turmeric","1 tsp"),("onion","2")],["Fry herbs in oil until very dark and fragrant (20 min).","Brown lamb with onion and turmeric.","Combine with herbs, soaked beans, pierced dried limes.","Simmer 2.5 hr. Serve with saffron rice."],460,38,22,24,"Iran's most beloved stew — the dried limes give a unique sour note unmatched by anything else.")
add("ir-002","Chelo Kebab","Persian","persian","Middle Eastern","grilled",40,"Medium",[],["lamb","saffron","grilled","national dish"],4,[("lamb mince","600g"),("grated onion","1 large"),("saffron","pinch"),("sumac","1 tsp"),("salt","1 tsp"),("butter","2 tbsp"),("saffron rice","4 cups")],["Mix lamb with grated onion, salt.","Shape onto flat skewers.","Grill over charcoal 3–4 min each side.","Serve over saffron rice with grilled tomatoes, butter, and sumac."],580,36,68,18)
add("ir-003","Ash Reshteh","Persian","persian","Middle Eastern","soup",90,"Medium",["vegetarian"],["noodles","spinach","herb soup","new year"],6,[("fresh noodles","300g"),("spinach","400g"),("kidney beans","1 can"),("chickpeas","1 can"),("onion","2"),("turmeric","1 tsp"),("kashk (whey)","4 tbsp"),("dried mint","1 tbsp"),("fried onion","for serving")],["Sauté onion with turmeric until golden.","Add beans, chickpeas, water. Simmer 30 min.","Add spinach and noodles. Cook 15 min.","Top with kashk, fried onion, dried mint."],380,14,52,10)

# ─── SOUTH AFRICAN ────────────────────────────────────────────────────────────
add("za-001","Bobotie","South African","south-african","African","stew",75,"Medium",[],["beef","sweet-savoury","cape malay","baked"],6,[("ground beef","800g"),("onion","2"),("garlic","3 cloves"),("curry powder","2 tbsp"),("turmeric","1 tsp"),("apricot jam","2 tbsp"),("bread soaked in milk","2 slices"),("eggs","2"),("milk","300ml"),("bay leaves","2")],["Fry onion, garlic, spices. Add beef.","Mix in bread, jam, seasoning.","Press into baking dish. Pour over egg-milk custard.","Bake at 180°C for 35 min."],480,28,28,24,"A Cape Malay masterpiece — the sweet-savoury-spiced custard topping is like nothing else.")
add("za-002","Braai Boerewors","South African","south-african","African","grilled",30,"Easy",[],["sausage","bbq","south african"],4,[("boerewors sausage","800g"),("pap (maize porridge)","4 cups"),("chakalaka relish","1 cup"),("tomato gravy","2 cups")],["Coil boerewors on hot braai (grill).","Grill 15 min, turning carefully.","Serve with pap, chakalaka, and tomato gravy."],580,32,42,28)

# ─── HAWAIIAN ─────────────────────────────────────────────────────────────────
add("hw-001","Ahi Tuna Poke Bowl","Hawaiian","hawaiian","North American","bowl",20,"Easy",[],["poke","raw fish","rice bowl","fresh"],2,[("sushi-grade ahi tuna","300g"),("soy sauce","3 tbsp"),("sesame oil","1 tbsp"),("scallions","3"),("sesame seeds","1 tbsp"),("avocado","1"),("edamame","½ cup"),("sushi rice","2 cups"),("sriracha mayo","2 tbsp")],["Cube tuna. Marinate with soy and sesame oil 10 min.","Cook and season sushi rice.","Arrange rice, tuna, avocado, edamame.","Drizzle sriracha mayo. Top with sesame and scallions."],520,38,48,20,"Poke means 'to slice' in Hawaiian — originally a simple fisherman's snack.")
add("hw-002","Loco Moco","Hawaiian","hawaiian","North American","eggs",30,"Easy",[],["rice","beef","egg","hawaiian"],2,[("ground beef","400g"),("eggs","2"),("white rice","2 cups"),("beef gravy","400ml"),("onion","1")],["Form beef patties, cook to your liking.","Fry eggs sunny-side up.","Serve rice topped with beef patty and egg.","Pour hot gravy generously over everything."],680,38,72,22)

# ─── AUSTRALIAN ───────────────────────────────────────────────────────────────
add("au-001","Meat Pie","Australian","australian","Oceanian","stew",90,"Medium",[],["pastry","beef","comfort"],4,[("shortcrust pastry","500g"),("puff pastry","250g"),("ground beef","600g"),("onion","2"),("beef stock","300ml"),("Worcestershire sauce","2 tbsp"),("flour","2 tbsp"),("tomato paste","2 tbsp")],["Brown beef with onion. Add paste, flour, stock, Worcestershire.","Simmer 20 min until thick.","Line pie tin with shortcrust. Fill with cooled beef.","Top with puff pastry. Brush with egg. Bake 200°C 25 min."],620,28,58,30)
add("au-002","Pavlova","Australian","australian","Oceanian","dessert",90,"Medium",["vegetarian","gluten-free"],["dessert","meringue","cream","summer"],8,[("egg whites","6"),("caster sugar","300g"),("cornstarch","2 tsp"),("white vinegar","1 tsp"),("heavy cream","400ml"),("passionfruit","4"),("strawberries","200g"),("kiwi fruit","2")],["Beat egg whites to stiff peaks. Add sugar gradually.","Fold in cornstarch and vinegar.","Shape on baking paper. Bake 130°C for 1.5 hr. Cool in oven.","Top with whipped cream and seasonal fruit."],320,5,52,10)

# ─── SOUTHERN AMERICAN ────────────────────────────────────────────────────────
add("sa-001","Shrimp and Grits","Southern American","southern-american","North American","stew",40,"Medium",[],["shrimp","grits","southern","comfort"],4,[("large shrimp","400g"),("stone-ground grits","1 cup"),("andouille sausage","200g"),("onion","1"),("bell pepper","1"),("garlic","3 cloves"),("chicken stock","400ml"),("heavy cream","100ml"),("butter","4 tbsp"),("cheddar","100g")],["Cook grits in stock and cream. Finish with butter and cheddar.","Sauté sausage, onion, pepper, garlic.","Add shrimp, cook 3 min until pink.","Ladle over grits."],580,32,42,28)
add("sa-002","Biscuits and Gravy","Southern American","southern-american","North American","bread",30,"Easy",[],["breakfast","sausage","comfort","southern"],4,[("flour","2 cups"),("baking powder","1 tbsp"),("butter","6 tbsp cold"),("buttermilk","¾ cup"),("pork sausage","300g"),("milk","2 cups"),("black pepper","½ tsp")],["Mix flour, baking powder, cut in butter. Add buttermilk.","Shape and bake biscuits at 220°C 12 min.","Brown sausage, make roux. Add milk, cook until thick.","Split biscuits and smother with gravy."],580,18,58,28)

# ─── CUBAN ────────────────────────────────────────────────────────────────────
add("cu-001","Ropa Vieja","Cuban","cuban","Caribbean","stew",120,"Medium",[],["beef","shredded","comfort","national dish"],4,[("beef flank steak","800g"),("canned tomatoes","400g"),("red bell peppers","2"),("onion","2"),("garlic","4 cloves"),("cumin","1 tsp"),("oregano","1 tsp"),("olives","50g"),("capers","2 tbsp")],["Boil beef until tender, 1.5 hr. Shred.","Sauté onion, pepper, garlic. Add tomatoes, cumin, oregano.","Add shredded beef, olives, capers.","Simmer 20 min. Serve with rice and black beans."],380,36,18,14,"Ropa vieja means old clothes — the shredded meat resembles torn fabric.")
add("cu-002","Cuban Black Beans","Cuban","cuban","Caribbean","stew",90,"Easy",["vegan","gluten-free"],["black beans","sofrito","comforting"],6,[("black beans","2 cans"),("onion","1"),("green pepper","1"),("garlic","4 cloves"),("olive oil","3 tbsp"),("cumin","1 tsp"),("oregano","1 tsp"),("bay leaf","2"),("sugar","½ tsp"),("apple cider vinegar","1 tbsp")],["Sauté onion, pepper, garlic in olive oil.","Add beans, cumin, oregano, bay leaves.","Simmer 30 min. Add sugar and vinegar.","Serve over white rice with Cuban bread."],280,12,48,6)

# ─── SWEDISH ──────────────────────────────────────────────────────────────────
add("sw-001","Köttbullar","Swedish","swedish","European","grilled",40,"Easy",[],["meatballs","swedish","comfort"],4,[("ground pork","300g"),("ground beef","200g"),("breadcrumbs","4 tbsp"),("egg","1"),("onion","1 grated"),("allspice","½ tsp"),("cream","4 tbsp"),("butter","2 tbsp"),("cream sauce","400ml"),("lingonberry jam","for serving")],["Mix all meatball ingredients. Form small balls.","Fry in butter until golden all over.","Make cream sauce in same pan.","Serve with mashed potato, lingonberry jam, and pickled cucumber."],480,28,24,28)
add("sw-002","Gravlax","Swedish","swedish","European","seafood",10,"Easy",["gluten-free"],["salmon","cured","nordic"],8,[("salmon fillet","1kg"),("salt","4 tbsp"),("sugar","2 tbsp"),("dill","1 large bunch"),("white pepper","1 tsp"),("mustard-dill sauce","for serving")],["Mix salt, sugar, pepper. Rub over salmon.","Cover with dill. Sandwich two fillets.","Refrigerate with weight on top for 48 hr.","Slice paper-thin on the diagonal."],180,18,4,10)

# ─── GERMAN ───────────────────────────────────────────────────────────────────
add("de-001","Schnitzel","German","german","European","grilled",25,"Easy",[],["pork","breaded","quick"],4,[("pork loin","4 thin slices"),("flour","4 tbsp"),("eggs","2"),("breadcrumbs","2 cups"),("oil","for frying",""),("lemon","1"),("parsley","handful")],["Pound pork to ¼ inch. Season.","Dredge in flour, egg, breadcrumbs.","Fry in ½ inch oil over medium-high heat 2–3 min each side.","Serve immediately with lemon and potato salad."],480,34,38,18)
add("de-002","Sauerbraten","German","german","European","stew",180,"Hard",[],["beef","marinated","sour","festive"],6,[("beef chuck","1.5kg"),("red wine vinegar","500ml"),("red wine","250ml"),("onion","2"),("carrot","2"),("bay leaves","3"),("juniper berries","5"),("gingersnap cookies","8"),("sugar","2 tbsp")],["Marinate beef in vinegar, wine, veg, spices 3 days.","Brown beef. Strain and reserve marinade.","Braise in marinade 2 hr.","Add crumbled gingersnaps to sauce to thicken and sweeten."],520,36,32,24)

# ─── RUSSIAN ──────────────────────────────────────────────────────────────────
add("ru-001","Borscht","Russian","russian","European","soup",60,"Medium",["vegetarian-option"],["beet","soup","sour cream"],6,[("beets","3 large"),("cabbage","½ head"),("carrot","2"),("onion","2"),("potato","3"),("canned tomatoes","400g"),("vinegar","2 tbsp"),("sugar","1 tsp"),("sour cream","for serving"),("dill","for serving")],["Grate beets. Sauté onion, carrot, beets with tomatoes.","Add cabbage, potato, and 1.5L stock. Simmer 25 min.","Season with vinegar, sugar, salt.","Serve with sour cream and fresh dill."],180,6,30,4)
add("ru-002","Beef Stroganoff","Russian","russian","European","stew",30,"Easy",[],["beef","mushroom","cream","classic"],4,[("beef sirloin","500g"),("mushrooms","300g"),("onion","1"),("sour cream","200ml"),("beef stock","200ml"),("mustard","1 tsp"),("Worcestershire sauce","1 tbsp"),("butter","3 tbsp"),("egg noodles","for serving")],["Slice beef thin. Brown quickly in hot butter in batches.","Sauté onion and mushrooms.","Add stock, mustard, Worcestershire. Simmer 5 min.","Add sour cream off heat. Serve over egg noodles."],480,32,28,26)

# ─── POLISH ───────────────────────────────────────────────────────────────────
add("pl-001","Pierogi","Polish","polish","European","noodles",60,"Medium",["vegetarian"],["dumplings","potato","cheese","comfort"],6,[("flour","3 cups"),("egg","1"),("warm water","¾ cup"),("potatoes","600g"),("farmer's cheese","200g"),("onion","2"),("butter","3 tbsp"),("sour cream","for serving")],["Make dough. Rest 30 min. Roll thin.","Boil potatoes, mash with cheese and fried onion.","Cut circles, fill with potato mix, seal edges.","Boil 5 min, then pan-fry in butter until golden. Serve with sour cream."],480,14,68,16)
add("pl-002","Bigos","Polish","polish","European","stew",120,"Medium",[],["sauerkraut","pork","hunter's stew"],6,[("sauerkraut","1kg"),("pork shoulder","400g"),("smoked sausage","300g"),("dried mushrooms","30g"),("onion","2"),("canned tomatoes","400g"),("bay leaves","3"),("allspice","4"),("red wine","100ml")],["Soak dried mushrooms. Rinse sauerkraut.","Fry pork and sausage. Add onion.","Combine with sauerkraut, mushrooms, tomatoes, spices, wine.","Simmer 1.5 hr. Better the next day."],420,26,22,24)

# ─── ARGENTINIAN ──────────────────────────────────────────────────────────────
add("ar-001","Asado","Argentinian","argentinian","Latin American","grilled",120,"Medium",[],["bbq","beef","national dish","fire"],8,[("beef short ribs","1.5kg"),("chimichurri sauce","200ml"),("coarse salt","3 tbsp"),("provoleta (provolone)","300g")],["Build wood fire, let it burn down to coals.","Salt meat generously.","Grill ribs bone-down over medium heat 1–1.5 hr.","Serve with chimichurri and grilled provoleta."],620,46,0,46)
add("ar-002","Empanadas","Argentinian","argentinian","Latin American","stew",60,"Medium",[],["pastry","beef","baked","snack"],12,[("flour","3 cups"),("butter","100g"),("egg","2"),("beef mince","400g"),("onion","2"),("egg hard-boiled","2 chopped"),("olives","12"),("cumin","1 tsp"),("paprika","1 tsp")],["Make pastry, chill 30 min.","Cook beef filling with onion, spices, olives, eggs.","Fill pastry circles, fold and crimp.","Bake at 200°C 20 min or deep fry."],320,14,32,16)

# ─── COLOMBIAN ────────────────────────────────────────────────────────────────
add("co-001","Bandeja Paisa","Colombian","colombian","Latin American","rice",90,"Medium",[],["rice","beans","sausage","national"],4,[("white rice","2 cups"),("red beans","2 cans"),("ground beef","400g"),("chicharrón (fried pork skin)","200g"),("chorizo","2"),("fried egg","4"),("green plantain","2"),("avocado","2"),("hogao tomato sauce","200ml")],["Cook beans with hogao sauce and spices.","Fry ground beef, cook chorizo, fry chicharrón.","Fry plantain slices until golden.","Arrange everything on one large plate — rice, beans, meats, egg, plantain, avocado."],980,52,88,42,"Colombia's most generous dish — a platter that feeds you for the whole day.")
add("co-002","Ajiaco","Colombian","colombian","Latin American","soup",90,"Medium",["gluten-free"],["soup","potato","chicken","bogotá"],4,[("chicken breasts","600g"),("papa criolla (small yellow potato)","400g"),("papa pastusa (regular potato)","400g"),("papa sabanera (purple potato)","200g"),("guasca herb","4 sprigs"),("ears of corn","2"),("heavy cream","100ml"),("capers","3 tbsp")],["Simmer chicken with all potatoes and guasca for 1 hr.","Remove chicken, shred.","Papa criolla will dissolve to thicken soup.","Serve with cream, capers, and avocado."],380,28,48,10)

# ─── FUSION ───────────────────────────────────────────────────────────────────
add("fu-001","Korean Beef Tacos","Fusion","fusion","Fusion / Modern","tacos",30,"Easy",[],["korean","mexican","fusion","tacos"],4,[("beef ribeye","500g"),("soy sauce","3 tbsp"),("gochujang","1 tbsp"),("sesame oil","1 tbsp"),("garlic","3 cloves"),("pear","¼ grated"),("corn tortillas","12"),("kimchi","100g"),("sriracha mayo","4 tbsp"),("scallions","4")],["Marinate beef in soy, gochujang, sesame, garlic, pear.","Grill over high heat 2 min each side.","Warm tortillas. Assemble beef, kimchi, sriracha mayo, scallions."],380,24,32,14)
add("fu-002","Ramen Burger","Fusion","fusion","Fusion / Modern","burger",45,"Hard",[],["burger","ramen","fusion","creative"],2,[("ramen noodles cooked","2 servings"),("egg","1"),("ground beef","300g"),("American cheese","2 slices"),("shoyu tare","2 tbsp"),("scallions","3"),("sesame seeds","1 tbsp")],["Mix cooked ramen with egg. Form into round patties.","Pan-fry ramen buns until crispy and set.","Cook beef patties. Glaze with shoyu tare.","Assemble: ramen bun, beef, cheese, scallions."],580,34,52,22)
add("fu-003","Miso Butter Salmon","Fusion","fusion","Fusion / Modern","seafood",20,"Easy",[],["salmon","miso","japanese","quick"],2,[("salmon fillets","2"),("white miso","2 tbsp"),("butter","2 tbsp"),("mirin","1 tbsp"),("soy sauce","1 tbsp"),("honey","1 tsp"),("scallions","3"),("sesame seeds","1 tsp")],["Mix miso, butter, mirin, soy, honey into paste.","Coat salmon fillets.","Broil or pan-fry 4–5 min.","Serve over rice with scallions and sesame."],380,32,12,22)

print(f"Generated {len(R)} recipes")

# Output TypeScript
out = "// Auto-generated recipe dataset — do not edit manually\n"
out += 'import type { ExternalRecipe } from "@/lib/externalTypes";\n\n'
out += "export const EXPLORE_RECIPES: ExternalRecipe[] = "
out += json.dumps(R, indent=2, ensure_ascii=False)
out += ";\n"

with open("src/data/exploreRecipes.ts", "w") as f:
    f.write(out)

print("Written to src/data/exploreRecipes.ts")
