#!/usr/bin/env python3
"""Convert /tmp/recipe-image-map.json into src/data/macroRecipePhotos.ts (shared
by the app + website via getRecipeImage)."""
import json, os
m = json.load(open("/tmp/recipe-image-map.json"))
# stable ordering
items = sorted(m.items())
lines = [
    "// Real recipe photos for the expanded catalog (macro-recipe dishes),",
    "// sourced from food publishers via image search and validated (HTTP 200,",
    "// image content-type, min size). Generated by scripts/image_fetcher.py.",
    "// id -> image URL. Consumed by getRecipeImage() for both web + mobile.",
    "export const MACRO_RECIPE_PHOTOS: Record<string, string> = {",
]
for k, v in items:
    vv = v.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'  {json.dumps(k)}: "{vv}",')
lines.append("};")
out = "/Users/justinsuo/waivy/src/data/macroRecipePhotos.ts"
open(out, "w").write("\n".join(lines) + "\n")
print(f"wrote {out} with {len(items)} photos")
