// Auto-generated by scripts/fetchRecipePhotos.ts — do not edit manually.
// Regenerate:  npx tsx scripts/fetchRecipePhotos.ts
// Generated:   2026-06-03
// Coverage:    17/859 dish-specific Wikimedia Commons photos
// (Entries with non-food images removed; remaining entries are verified food photos)
export const RECIPE_PHOTO_MAP: Record<string, string> = {
  "jp-miso-soup": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Miso_Soup_001.jpg/960px-Miso_Soup_001.jpg",
  "jp-tkj": "https://upload.wikimedia.org/wikipedia/commons/0/09/Tamago_kake_gohan.jpg",
  "jp-ochazuke": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Instant_chazuke_by_shibainu.jpg/960px-Instant_chazuke_by_shibainu.jpg",
  "in-khichdi": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Masala_Khichadi.jpg/960px-Masala_Khichadi.jpg",
  "in-chole-bhature": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Chole_Bhature%2C_a_popular_North_Indian_dish.jpg/960px-Chole_Bhature%2C_a_popular_North_Indian_dish.jpg",
  "in-chicken-karahi": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Kadai_chicken_%28karahi%29.jpg",
  "in-poha": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Makka_Poha.jpg/960px-Makka_Poha.jpg",
  "in-pulao": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/VEGETABLE_PULAO_~_An_Indian_cuisine_made_from_fried_rice_mixed_with_fried_vegetables.jpg/960px-VEGETABLE_PULAO_~_An_Indian_cuisine_made_from_fried_rice_mixed_with_fried_vegetables.jpg",
  "la-khao-tom": "https://upload.wikimedia.org/wikipedia/commons/8/85/Lao_cuisine_khaotom.jpg",
  "bn-ambuyat": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Ambuyat_in_Bandar_Seri_Begawan_Brunei.jpg/960px-Ambuyat_in_Bandar_Seri_Begawan_Brunei.jpg",
  "mw-nsima": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Nsima_Relishes.JPG",
  "ph-pancit-canton": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pancit_Ilonggo_Style_-_12110089845.jpg/960px-Pancit_Ilonggo_Style_-_12110089845.jpg",
  "id-rawon": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bumbu_Rawon.jpg/960px-Bumbu_Rawon.jpg",
  "sg-chicken-rice": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Hainanese_chicken_rice_%28in_Macau%29.jpg/960px-Hainanese_chicken_rice_%28in_Macau%29.jpg",
  "ro-fasole-cu-carnati": "https://upload.wikimedia.org/wikipedia/commons/8/83/Fasole_cu_afumatura.jpg",
  "ro-ghiveci": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Ghiveci_-_panoramio.jpg/960px-Ghiveci_-_panoramio.jpg",
  "bg-shopska-salad": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/02021_0385_Shopska_salad%2C_Beskids.jpg/960px-02021_0385_Shopska_salad%2C_Beskids.jpg",
};
